#!/usr/bin/env python
from sys import stderr
COMMENTS=("%s", "'%s")

def ihash(value, ret = 0):
    for c in value:
        ret = (ord(c.lower()) +((65599 * ret) & 0xffffffff)) & 0xffffffff
    return ret

def a_ihash(sections, names):
    for section in sections:
        sectionhash = ihash('*', ihash(section))
        for rawname in names:
            for com in COMMENTS:
                name = com % rawname
                ret = ihash(name, sectionhash)
                yield section, name, ret

all_gamemodes = [
    "ARAM",
    "CLASSIC",
    "FIRSTBLOOD",
    "ODIN",
    "ONEFORALL",
    "TUTORIAL",
    "ASCENSION",
    "URF",
    "ASSASSINATE",
    "DARKSTAR",
    "SIEGE",
    "STARGUARDIAN",
    "KingPoro",
]

all_mutators = [
    *all_gamemodes,
    "Bilgewater",
    "Clarity",
    "Default",
    "NightmareBots",
    "NightmareBotsDebug",
    "TagTeam",
]

all_stats = [
    "BattleFury",
    "BloodWell",
    "DragonFury",
    "Energy",
    "Ferocity",
    "GnarFury",
    "Heat",
    "MP",
    "Mana",
    "None",
    "Other",
    "Rage",
    "Shield",
    "Wind",
]

def map_vars(*args):
    return [
        *args,
        *[ "Map%d_%s" % (x,a) for a in args for x in range(0, 15) ],
    ]

#FIXME: Blacklisted stuff: "UnitBarData", "MapObjects", "GeneralCharacterData"

all_inibin_fixlist = [
# TODO: LEVELS/MapX/AtmosphereMutators.inibin (Atmosphere*mutators)
# LEVELS/MapX/Audio.inibin
    [
        [ 
            "Default",
            *[ 'GameMode_%s' % m for m in all_gamemodes ],
        ],
        [
            "AmbientEvent",
            "DefeatMusic",
            "ReverbPreset",
            "ThemeMusic",
            "VictoryMusic",
        ],
    ],
    [
        [ "SoundBanks", ],
        [
            "EventLookupTable",
            "NumOfSoundBanks",
        ],
    ],
# LEVELS/MapX/clouds.inibin
    [
        [ "Clouds", ],
        [
            "SpeedU",
            "SpeedV",
            "Texture",
            "Tile",
        ],
    ],
# LEVELS/MapX/DeathTimes.inibin
    [
        [ "DeathTimeScaling", ],
        [
            "IncrementTime",
            "PercentCap",
            "PercentIncrease",
            "StartTime",
        ],
    ],
    [
        [ "DeathTimeSettings", ], 
        [
            "AllowDeathTimeMods",
            "StartDeathTimerForZombies",
        ],
    ],
    [
        [ "DeathWaveRespawn", ], 
        [
            "WaveRespawnInterval",
        ],
    ],
    [
        [ "ExpGrantedOnDeath", ], 
        [
            "BaseExpMultiple",
            "LevelDifferenceExpMultiple",
            "MinimumExpMultiple",
        ],
    ],
    [
        [ "TimeDeadPerLevel", "TimeDeadPerLevelTutorial" ],
        [
            *[ "Level%02d" % x for x in range(0, 31) ]
        ],  
    ],
# LEVELS/MapX/Items.inibin
    [
        [ 
            "ItemInclusionList",
            "UnpurchasableItemList",
            "UnpurchasableItemListTutorial",
            *[ "UnpurchasableItemList_%s" % x for x in all_mutators ],
        ],
        [
            *[ "Item%d" % x for x in range(0, 200) ]
        ],
    ],
# LEVELS/MapX/Gamma.inibin
    [
        [ "Gamma", ],
        [
            "Brightness",
            "Contrast",
            "Gamma",
            "Level",
        ],
    ],
# LEVELS/MapX/Graphics.inibin
    [
        [ "TextureQuality", ],
        [
            "Default",
            "Effects",
            "Grass",
            "Terrain",
            "World",
        ],
    ],
    [
        [ "SimpleEnvironment", ],
        [
            "HighlightColor",
        ],
    ],
# LEVELS/MapX/Mission.inibin
    [
        [ 
            "ExtraSummonerItem",
            "ExtraSummonerItemTutorial",
        ],
        [ 
            "Icon",
            "ItemID",
            "Tooltip",
        ],
    ],
    [
        [ "LoadScreen", ],
        [ "ScreenToLoad", ],
    ],
    [
        [ "BehaviorTreeMetaData", ],
        [
            "BehaviorTreeNodeLibraryCommon",
            "BehaviorTreeNodeLibraryClient",
        ],
    ],
    [
        [ "General", ],
        [
            "RelativeColorization",
            "StringID",
        ],
    ],
# LEVELS/MapX/MonsterDataTableX.inibin
    [
        [ 
            "AbilityPower", 
            "AttackDamage",
            "Armor",
            "Experience",
            "Gold",
            "Health",
            "MagicResist",
        ],
        [
            *[ "Level%d" % x for x in range(0, 20) ],
        ],
    ],
# LEVELS/MapX/NeutralTimers.inibin
    [
        [ "General", ],
        [ 
            *[ "Element%d" % x for x in range(0, 10) ],
            *[ "Element%d_%s" % (x, y) for x in range(0, 10) for y in [
                    "Default",
                    "Colorblind",
                    "Spectator",
                ]
            ],
            "HudFrameHandle",
            "HudGroup",
            "RespawnTime",
            "TimerTooltip",
            "TimerWarningThreshold",
        ],
    ],
    [
        [
            *[ "Timer%d" % x for x in range(0, 10) ],
        ],
        [
            "HudHandleText",
            "HudHandleIcon",
            *[ "HudHandleIcon_%s" % x for x in [
                    "Default",
                    "Colorblind",
                    "Spectator",
                ]
            ],
            "TimerType",
            "TooltipName",
            "TooltipRespawn",
            "TimerWarningThreshold",
        ],
    ],
# LEVELS/MapX/ExpCurve.inibin
    [
        [ "EXP", "EXPTutorial", ], 
        [
            *[ "Level%d" % x for x in range(0, 31) ]
        ]
    ],
# LEVELS/MapX/ExpCurve.inibin
    [
        [ "Experience", ],
        [ 
            * [ "PlayerMinionSplitXP%d" % x for x in range(1, 6) ],
        ],
    ],
    [
        [ "BehaviorTreeMetaData", ],
        [
            "BehaviorTreeNodeLibraryCommon",
            "BehaviorTreeNodeLibraryClient",
            "BehaviorTreeNodeLibraryServer",
        ],
    ],
    [
        [ "LoadScreen", ],
        [
            "ScreenToLoad",
        ],
    ],
# LEVELS/MapX/Particles.inibin
    [
        [ "FootSteps", ],
        [
            *[ "EffectName%d" % x for x in range(0,4) ],
            "EmitterBone",
            "EmitterRotation",
            *[ "Key%d" % x for x in range(0,4) ],
            *[ "State%d" % x for x in range(0,4) ],
        ],
    ],
# LEVELS/MapX/PerSide.inibin
    [
        [ "Camera", ],
        [
            "ChaosXOffset",
            "ChaosYOffset",
            "ChaosZOffset",
            "OrderXOffset",
            "OrderYOffset",
            "OrderZOffset",
        ],
    ],
# LEVELS/MapX/StatsProgression.inibin
    [
        [ "PerLevelStatsFactor", ],
        [
            *[ "Level%d" % x for x in range(0, 31) ]
        ]
    ],
# LEVELS/MapX/ShadowSettings.inibin
    [
        [ "Shadow", ],
        [
            "ShadowBias",
            "ShadowFadeMinY",
            "ShadowFadeRange",
        ],
    ],
# LEVELS/MapX/terrain.inibin
# LEVELS/MapX/envlighting.inibin
    [
        [ "AlphaTest", ],
        [ 
            "Cut_off",
        ],
    ],
    [
        [ "ColorMap", ],
        [
            "Enable", 
        ],
    ],
    [
        [ "HeightBlending", ],
        [
            "Enable", 
            "Layer0_scale",
            "Layer1_scale",
            "Layer2_scale",
            "Layer3_scale",
        ],
    ],
    [
        [ "Environment", ],
        [
            "CullingDistanceOverride",
            "DevMark",
            "DisablePointLights",
            "Lighting",
            "Renderer",
            "ShadowBlur",
            "ShadowColor",
            "ShadowDynamicOnly",
            "UseAlphaBlend",
        ],
    ],
    [
        [ "FoW", ],
        [
            "Blend",
            "BlurKernelSigma",
            "Color_red",
            "Color_green",
            "Color_blue",
            "Fade",
            "FadeFinish",
            "FadeStart",
            "EdgeEnhancement",
            "EdgeTintPoint",
            "Upscale",
        ],
    ],
    [
        [ "Fog", ],
        [
            "Red",
            "Green",
            "Blue",
            "Opacity",
            "Min_height",
            "Max_height",
            "Min_radius",
            "Max_radius",
            "Min_opaque_height",
            "Max_opaque_height", 
            "UseOpacityMap",
            "Enable",
        ],
    ],
# DATA/Images/UI/GameBar
    [
        [ "Animation", ],
        [
            "AnimationTime",
            "FrameCount",
        ],
    ],
    [
        [ "Frames", ],
        [
            *[ "Frame%d" % x for x in range(0, 25) ],
        ],
    ],
# DATA/Globals/ABGroups.inibin
    [
        [ "Settings", ],
        [
            "EnabledGroups",
        ],
    ],
    [
        [ "Control", ],
        [
            "Weight",
            "Features",
        ],
    ],
    [
        [ "Everything", ],
        [
            "Weight",
            "Features",
        ],
    ],
# DATA/Globals/Critical.inibin
    [
        [ "Karma", ], 
        [
            *[ "Critical%d" % c for c in range(0, 201) ],
        ],
    ],
# DATA/Globals/ExcludedItems.inibin
    [
        [ "ExcludedItems", ],
        [
            # TODO: find upper limit
            *[ "ExcludedItem%d" % x for x in range(1, 200) ],
        ],
    ],
# DATA/Globals/LimitedQuanitityItems.inibin
    [
        [ "LimitedQuanitityItems", ],
        [
            # TODO: find upper limit
            *[ "LQItem%d" % x for x in range(1, 200) ],
        ],
    ],
# DATA/Globals/Tips.inibin
    [
        [
            "Global",
            *all_gamemodes,
        ], 
        [
            "MaxViewable",
        ],
    ],
    [
        [
            "Global",
        ], 
        [
            "DialogueClosedSound",
            "DialogueOpenedSound",
            "MaxViewable",
            "TipRecievedSound",
        ],
    ],
# DATA/Globals/GameMutatorExpansions.inibin
    [
        [
            *all_mutators,
        ],
        [
            *[ "Mutator%d" % x for x in range(0, 13) ],
        ],
    ],
# DATA/Globals/Bounty.inibin
    [
        [
            "Global",
            *all_gamemodes,
        ], 
        [
            "AssistDeathstreakReduction",
            "AssistDurationOverride",
            "AssistGoldPerStreak",
            "AssistGoldStreakCap",
            "AssistGoldStreakStart",
            "AssistPoolMax",
            "AssistPoolMaxValueTime",
            "AssistPoolMin",
            "AssistPoolMinValueTime",
            "AssistStreakBonus",
            "AssistStreakMin",
            "BaseGold",
            "BountyRoundDownIncrement",
            "DeathStreakPenalty",
            "FirstBloodBonus",
            "GoldPoolForAssist",
            "KillStreakBonus",
            "MaxKillStreakBonus",
            "MinAssistsForStreak",
            "MinDeathsForStreak",
            "MinDeathStreakPenalty",
            "MinionGoldDeathstreakReductionRatio",
            "MinionGoldValueForBounty",
            "MinKillsForStreak",
            "MinMinionGoldValueForBounty",
            "PercentBountyResetOnDeath",
            "TimeBasedMinValuePercent",
            "TimeToMaxValueInSeconds",
            "TimeToMinValueInSeconds",
        ]
    ],
    [
        [ "DeathStreak", ],
        [
            "DeathStreakPenalty",
            "MinDeathsForStreak",
            "MinDeathStreakPenalty",
        ],
    ],
    [
        [ "KillStreak", ],
        [
            "KillStreakBonus",
            "MaxKillStreakBonus",
            "MinKillsForStreak",
        ],
    ],
# DATA/Globals/ColorSettings.inibin
    [
        [ "ColorChaos", "ColorOrder", ],
        [
            "PlayerColorHighlightBlue",
            "PlayerColorHighlightGreen",
            "PlayerColorHighlightRed",
        ],
    ],
# DATA/Globals/*_Stats.inibin
    [
        [
            "HeroStats",
        ],
        [
            "ID",
            "NAME",
            "SKIN",
            "TEAM",
            "WIN",
            "EXP",
            "LEVEL",
            "GOLD_SPENT",
            "GOLD_EARNED",
            "NUM_DEATHS",
            "CHAMPIONS_KILLED",
            "ASSISTS",
            "BARRACKS_KILLED",
            "TURRETS_KILLED",
            "HQ_KILLED",
            "MINIONS_KILLED",
            "NEUTRAL_MINIONS_KILLED",
            "SUPER_MONSTER_KILLED",
            "LARGEST_KILLING_SPREE",
            "KILLING_SPREES",
            "LARGEST_MULTI_KILL",
            "TOTAL_DAMAGE_DEALT",
            "PHYSICAL_DAMAGE_DEALT_PLAYER",
            "MAGIC_DAMAGE_DEALT_PLAYER",
            "TOTAL_DAMAGE_DEALT_TO_CHAMPIONS",
            "PHYSICAL_DAMAGE_DEALT_TO_CHAMPIONS",
            "MAGIC_DAMAGE_DEALT_TO_CHAMPIONS",
            "TOTAL_DAMAGE_TAKEN",
            "PHYSICAL_DAMAGE_TAKEN",
            "MAGIC_DAMAGE_TAKEN",
            "DOUBLE_KILLS",
            "TRIPLE_KILLS",
            "QUADRA_KILLS",
            "PENTA_KILLS",
            "UNREAL_KILLS",
            "ITEMS_PURCHASED",
            "CONSUMABLES_PURCHASED",
            "SPELL1_CAST",
            "SPELL2_CAST",
            "SPELL3_CAST",
            "SPELL4_CAST",
            "SUMMON_SPELL1_CAST",
            "SUMMON_SPELL2_CAST",
            "LARGEST_CRITICAL_STRIKE",
            "TIME_PLAYED",
            "LONGEST_TIME_SPENT_LIVING",
            "TOTAL_TIME_SPENT_DEAD",
            "TOTAL_HEAL",
            "TOTAL_UNITS_HEALED",
            "FRIENDLY_TURRET_LOST",
            "FRIENDLY_DAMPEN_LOST",
            "FRIENDLY_HQ_LOST",
            "TOOK_FIRST_BLOOD",
            "WAS_AFK",
            "WAS_AFK_AFTER_FAILED_SURRENDER",
            "TIME_OF_FROM_LAST_DISCONNECT",
            "TIME_SPENT_DISCONNECTED",
            "NEVER_ENTERED_GAME",
            "TEAMMATE_NEVER_ENTERED_GAME",
            "ITEM0",
            "ITEM1",
            "ITEM2",
            "ITEM3",
            "ITEM4",
            "ITEM5",
            "ITEM6",
            "SIGHT_WARDS_BOUGHT_IN_GAME",
            "VISION_WARDS_BOUGHT_IN_GAME",
            "NODE_CAPTURE",
            "NODE_NEUTRALIZE",
            "NODE_KILL_OFFENSE",
            "TEAM_OBJECTIVE",
            "DEFEND_POINT_NEUTRALIZE",
            "NODE_KILL_DEFENSE",
            "NODE_TIME_DEFENSE",
            "LAST_STAND",
            "NODE_CAPTURE_ASSIST",
            "NODE_NEUTRALIZE_ASSIST",
            "TOTAL_PLAYER_SCORE",
            "OFFENSE_PLAYER_SCORE",
            "DEFENSE_PLAYER_SCORE",
            "COMBAT_PLAYER_SCORE",
            "OBJECTIVE_PLAYER_SCORE",
            "VICTORY_POINT_TOTAL",
            "TOTAL_SCORE_RANK",
            "PING",
            "TRUE_DAMAGE_DEALT_PLAYER",
            "TRUE_DAMAGE_TAKEN",
            "TRUE_DAMAGE_DEALT_TO_CHAMPIONS",
            "WARD_PLACED",
            "WARD_KILLED",
            "TOTAL_TIME_CROWD_CONTROL_DEALT",
            "NEUTRAL_MINIONS_KILLED",
            "NEUTRAL_MINIONS_KILLED_YOUR_JUNGLE",
            "NEUTRAL_MINIONS_KILLED_ENEMY_JUNGLE",
        ],
    ],
    [
        [ "MoveSpeed", ],
        [
            "MajorMovePenaltyCoefficient",
            "MajorMovePenaltyThreshold",
            "MinorMovePenaltyCoefficient",
            "MinorMovePenaltyThreshold",
            "SlowMovePenaltyCoefficient",
            "SlowMovePenaltyThreshold",
            "WallPathingFactor",
        ],
    ],
# DATA/Globals/Quests.inibin
    [
        [
            "PrimaryQuests", 
            "SecondaryQuests", 
            "Objectives",
        ],
        [
            *[ "%s%s" % (x, y) for x in [
                    "RecievedSound",
                    "CompletedSound",
                    "FailedSound",
                ] for y in [
                    "Effect",
                    "VO_ID",
                    "VO_Folder",
                ]
            ],
            "CompletedText",
            "FailedText",
            "MaxViewable",
            "RecievedText",
            "TitleText",
        ],
    ],
    [
        [ "Coefficients", ],
        [
            "MCoefficient",
            "NCoefficient",
        ],
    ],
# DATA/Menu_SC4/PARStates.inibin
    [
        [ *all_stats, ],
        [
            "NumStates",
            "ShowPAR",
            "ShowRegen",
            # TODO: GnarFurry has State5 ...
            *[ "State%dColor" % x for x in range(0, 3) ],
            *[ "State%dFadeColor" % x for x in range(0, 3) ],
            *[ "State%dVideoPrefix" % x for x in range(0, 3) ],
        ],
    ],
# DATA/Menu_SC4/HUD.inibin
    [
        [ "Texture", ],
        [
            "BaseBorder",
            "ButtonBG",
            "BaseFill",
            "BaseIcon",
            "IndicatorBG",
            "TowerBorder",
            "TowerFill",
            "TowerIcon",
        ],
    ],
    [
        [ 
            "Texture",
            *[ "Texture%d" % x for x in range(0, 4) ],
        ],
        [
            "Bot",
            "Mid",
            "Top",
        ],
    ],
    [
        [ "Position", ],
        [
            "BaseOffsetFromEdge",
            "LaneOffsetFromTopOfScreen",
            "SizeOfTowerDisplay",
        ],
    ],
# DATA/Menu_SC4/GeneralCharacterData.inibin
# TODO: Do we need this?
    [
        [ "AttackData", ],
        [ "AttackAutoInterruptPercent", ],
    ],
    [
        [ "GeneralDataHero", ],
        [ 
            "DefaultBoundingCylinderHeight",
            "DefaultBoundingCylinderRadius",
            "DefaultBoundingSphereRadius",
            "DefaultChampionCollisionRadius",
            "DefaultHealthPerMegaTick",
            "DefaultHealthPerTick",
            "FadeTimerForHealthBar",
            "FullHealthAlpha",
            "MaxHealthTicks",
            "ZeroHealthAlpha",
        ],
    ],
# DATA/LoadingScreen/
    [
        [ "Data", ],
        [
            *[ "Badge%d_ID" % x for x in range(0, 4) ],
            *[ "Badge%dTexU" % x for x in range(0, 4) ],
            *[ "Badge%dTexV" % x for x in range(0, 4) ],
            "BackgroundTexBotU",
            "BackgroundTexBotV",
            "BackgroundTexChaosOffset",
            "BackgroundTexU",
            "BackgroundTexV",
            "BadgeBorderTexHeight",
            "BadgeBorderTexU",
            "BadgeBorderTexV",
            "BadgeBorderTexWidth",
            "BadgeBorderTexU",
            "BadgeBorderTexV",
            "BadgeBorderTexWidth",
            "BadgeTexHeight",
            "BadgeTexWidth",
            *[ "BarTextUVs%du%d" % (x,y) for x in range(0, 4) for y in range(1,3) ],
            *[ "BarTextUVs%dv%d" % (x,y) for x in range(0, 4) for y in range(1,3) ],
            *[
                f % x for f in [
                    "Badge%dTexU",
                    "Badge%dTexV",
                    "Badge%d_ID",
                ] for x in range(0, 4)
            ],
            "BlackBoxHeight",
            "BlackBoxWidth",
            "BlackBoxX",
            "BlackBoxY",
            "CardBarHeightFactor",
            "CardBarWidthFactor",
            "CardBarXFactor",
            "CardBarYFactor",
            "CardHeightFixed",
            "CardWidthFixed",
            "ChampionBoxHeight",
            "ChampionBoxWidth",
            "ChampionBoxX",
            "ChampionBoxY",
            "ChampionCardHeightPercentage",
            "ChampionCardHorizontalLayout",
            "ChampionNameHeight",
            "ChampionNameHeightForLongString",
            "ChampionNameHeightHeightForLongString",
            "ChampionNameOffset",
            "ChampionTextBoxHeight",
            "ChampionTextBoxWidth",
            "ChampionTextBoxX",
            "ChampionTextBoxY",
            "ChaosCardHeightPercentage",
            "ChaosCardWidthPercentage",
            "ChaosCardXPercentage",
            "ChaosCardYPercentage",
            "DebugNumberOnChoas",
            "DebugNumberOnOrder",
            "DebugPing",
            "EnableVs",
            "Image",
            "ImageHeight",
            "ImageWidth",
            "LiveUpdate",
            "LongChampionName",
            "MessageOffsetX",
            "MessageOffsetY",
            "OrderCardHeightPercentage",
            "OrderCardWidthPercentage",
            "OrderCardXPercentage",
            "OrderCardYPercentage",
            "PercentageCompleteNoPingTextY",
            "PercentageCompleteTextX",
            "PercentageCompleteTextY",
            "PercentageMarginBetweenCardsX",
            "PercentageOfScreenBottomMargin",
            "PercentageOfScreenMiddleMargin",
            "PercentageOfScreenTopMargin",
            "PingBarMarginX",
            "PingBarMarginY",
            "PingBoxHeightFactor",
            "PingBoxOffsetFactorX",
            "PingBoxOffsetFactorY",
            "PingBoxWidthFactor",
            "ProfileIconHeightFactor",
            "ProfileIconOffsetFactorX",
            "ProfileIconOffsetFactorY",
            "ProfileIconWidthFactor",
            "ProgressbarBorderTexBotU",
            "ProgressbarBorderTexBotV",
            "ProgressbarBorderTexChaosOffset",
            "ProgressbarBorderTexU",
            "ProgressbarBorderTexV",
            "ProgressbarTexBotU",
            "ProgressbarTexBotV",
            "ProgressbarTexChaosOffset",
            "ProgressbarTexU",
            "ProgressbarTexV",
            "ProgressTextX",
            "ProgressTextY",
            "RankingsTextureAtlas",
            "RankingsTextureX",
            "RankingsTextureY",
            "SummonerNameHeight",
            "SummonerNameOffset",
            "SummonorBoxHeight",
            "SummonorBoxWidth",
            "SummonorSpellBox2X",
            "SummonorSpellBoxX",
            "SummonorSpellBoxY",
            "TeamsTextHeight",
            "TextureHeight",
            "TextureName",
            "Textures",
            "TextureWidth",
            "TextWidth",
            "TipsTextHeight",
            "UseSkinNames",
            "VsBorderTexBotU",
            "VsBorderTexBotV",
            "VsBorderTexU",
            "VsBorderTexV",
            "VsHeightFactor",
            "VsWidthFactor",
        ],
    ],
    [
        [ "VS", ],
        [
            "FontOutlineSize",
            "XPosPercentOfScreen",
            "YPosPercentOfScreen",
            "Scale",
        ],
    ],
    [
        [ "Background", ],
        [
            "ActualSizeHeight",
            "ActualSizeWidth",
            "Image",
            "ImageHeight",
            "ImageWidth",
            "LetterBoxBorderPercentage",
            "LoadBarHeightPercent",
            "LoadBarWidthPercent",
            "PercentLoadBarFromBottom",
            "SlowAutoReload",
        ],
    ],
    [
        [ 
            "GameMode",
            "Large",
            "ObjectiveText",
            "Ping",
            "Progress",
            "Small",
            "SmallForLongSkinNames",
            "Teams",
            "Title",
            "Tips",
        ],
        [
            "Bold",
            "ColorIn",
            "ColorInChaos",
            "ColorInOrder",
            "ColorInGreen",
            "ColorInOrange",
            "ColorInRed",
            "ColorInYellow",
            "ColorOut",
            "ColorOutChaos",
            "ColorOutOrder",
            "Font",
            "FontColorIn",
            "FontColorOut",
            "FontColorShadow",
            "FontOutlineSize",
            "FontResourceFile",
            "FontSize",
        ],
    ],
    [
        [ "FirstBlood", ],
        [
            "HBuffer",
            "HOffset",
            "Image",
            "ImageHeight",
            "ImageWidth",
            "VOffset",
        ],
    ],
    [
        [ "Teams", ],
        [
            "RegionChaosX",
            "RegionChaosY",
            "RegionOrderX",
            "RegionOrderY",
        ],
    ],
    [ 
        [ "ObjectiveText", ],
        [
            *[ "Objective%dLine%d" % (x,y) for x in range(1, 6) for y in range(1,3) ],
            "TimeBetweenMessagesSeconds",
        ],
    ],
    [
        [ "Ping", ],
        [
            "PingThresholdGreen",
            "PingThresholdOrange",
            "PingThresholdRed",
            "PingThresholdYellow",
        ],
    ],
    [
        [ "Progress", ],
        [
            "ForGroundProgressBarXOffset",
            "TextOffsetX",
            "TextOffsetXShadow",
            "TextOffsetY",
            "TextOffsetYShadow",
        ],
    ],
    [
        [ "Title", ],
        [ 
            "Text",
            "TitleOffScreenOffsetXPercent",
            "TitleScreenOffsetXPercent",
            "TitleScreenOffsetYPercent",
        ],
    ],
    [
        [ "TipsLeft", "TipsPBI", "TipsRight", ],
        [
            "RegionHeight",
            "RegionWidth",
            "RegionX",
            "RegionY",
            "TipsListFile",
            "TipsListSection",
            "TipsType",
        ],
    ],
    [
        [ *all_mutators ],
        [
            "Image",
            "DifficultyIconImage",
            "BotDifficultyY",
            "BotDifficultyX",
            "BotDifficultyHeight",
            "BotDifficultyWidth",
            "GameModeTextX",
            "BotDifficultySpacing",
            "GameModeTextHeight",
            "GameModeTextY",
        ],
    ],
    [
        [ 
            *[ "Texture%d" % x for x in range(0, 6) ], 
        ],
        [
            "Name",
            "Width",
            "Height",
            "Left",
            "Top",
        ],
    ],
# DATA/Levels/
    [
        [ "Data", ],
        [
            "MapID",
            "TutorialEnabled",
            "TutorialOnly",
            "TotalPlayers",
        ],
    ],
# DATA/Particles/ParticlesDefault.inibin
    [
        [ "GlobalEffects", ],
        [
            "ChampionIndicator",
            "ChaosBarrackDeath",
            "ChaosBarracksDamper",
            "ChaosBarracksDamperRespawn",
            "ChaosBarracksPoweredUp",
            "ChaosBarracksSpawn",
            "ChaosBuildingDeath",
            "ChaosHQDeath",
            "ChaosHQDeath2",
            "ChaosSpawnTurretBeam",
            "ComeHere",
            "CommandGround",
            "CommandTarget",
            "CursorCast",
            "CursorEnemyCastConfirm",
            "CursorEnemyCastConfirmLarge",
            "CursorFriendlyCastConfirm",
            "CursorFriendlyCastConfirmLarge",
            "CursorHoverEnemyUnit",
            "CursorHoverEnemyUnitLarge",
            "CursorHoverFriendlyUnit",
            "CursorHoverFriendlyUnitLarge",
            "CursorMoveTo",
            "CursorMoveToRed",
            "CursorSelectedEnemyUnit",
            "CursorSelectedEnemyUnitLarge",
            "CursorSelectedFriendlyUnit",
            "CursorSelectedFriendlyUnitLarge",
            "Danger",
            "Default",
            "DefendTarget",
            * [ "EffectName%d" % x for x in range(0, 40) ],
            "EnemyMinionDeath",
            "EnemyTurretDeath",
            "FocusTarget",
            "FountainHeal",
            * [ "FileName%d" % x for x in range(0, 40) ],
            "FriendlyMinionDeath",
            "FriendlyTurretDeath",
            "GoldAcquisition",
            "HeroAllyKilled",
            "HeroBlueKilledSpectator",
            "HeroEnemyKilled",
            "HeroKilledAssistedByPlayer",
            "HeroKilledByHero",
            "HeroKilledByNeutral",
            "HeroKilledByPlayer",
            "HeroRedKilledSpectator",
            "HeroRespawn",
            * [ "Key%d" % x for x in  range(0, 40) ],
            "LaserSightBeam",
            "LevelUp",
            "MIA",
            "MaxIdentifier",
            "MinionDeath",
            "MissingInstant",
            "MissingLingering",
            "OMW",
            "OrderBarrackDeath",
            "OrderBarracksDamper",
            "OrderBarracksDamperRespawn",
            "OrderBarracksPoweredUp",
            "OrderBarracksSpawn",
            "OrderBuildingDeath",
            "OrderHQDeath",
            "OrderHQDeath2",
            "OrderLaserSightBeam",
            "OrderSpawnTurretBeam",
            "Retreat",
            "StartHeroSpawn",
            * [ "State%d" % x for x in range(0, 40) ],
            "TurretDeath",
        ],
    ],
# DATA/Characters/HeroSpawnOffsets.inibin
    [
        [
            * [ "Chaos%d" % x for x in range(1, 7) ],
            * [ "Order%d" % x for x in range(1, 7) ],
        ],
        [
            * [ "Pos%d" % x for x in range(1, 7) ],
            * [ "Facing%d" % x for x in range(1, 7) ],
        ],
    ],
# spells, items, talents (everything is a buff -.-)
    [
        [ "BuffData", ], 
        [
            "AlternateName",
            "ApplyMaterialOnHitSound",
            "DisplayName",
            "Description",
            "DynamicExtended",
            "DynamicTooltip",
            "DeathRecapPriority",
            *[ "Effect%dLevel%dAmount" % (x, y) for x in range(1, 10) for y in range(0, 7) ],
            *[ "FloatStaticsDecimals%d" % x for x in range(1, 7) ],
            *[ "FloatVarsDecimals%d" % x for x in range(1, 7) ],
            "HideDurationInUI",
            "InventoryIcon",
            "ShowInActiveItemDisplay",
            "ShowInTrackerUI",
            "Sound_VOEventCategory",
        ],
    ],
# DATA/Items/metadata/categories.inibin
# DATA/Items/ItemGroups/*.inibin
# DATA/Items/X.inibin
    [
        [ "Attack", ],
        [
            "AttackSpeed",
            "CriticalStrike",
            "Damage",
            "LifeSteal",
        ],
    ],
    [
        [ "Builds", ],
        [
            *[ "Item%d" % x for x in range(1, 18) ]
        ],
    ],
    [
        [ "Categories", ],
        [
            "Active",
            "Armor",
            "ArmorPenetration",
            "AttackSpeed",
            "Aura",
            "Boots",
            "Consumable",
            "CooldownReduction",
            "CriticalStrike",
            "Damage",
            "GoldPer",
            "Health",
            "HealthRegen",
            "Jungle",
            "Internal",
            *[ "Item%d" % x for x in range(1, 18) ],
            "Lane",
            "LifeSteal",
            "MagicPenetration",
            "Mana",
            "ManaRegen",
            "Movement",
            "NonbootsMovement",
            "OnHit",
            "Slow",
            "SpellBlock",
            "SpellDamage",
            "SpellVamp",
            "Stealth",
            "Tenacity",
            "Trinket",
            "Vision",
        ],
    ],
    [
        [ "Data", ], 
        [
            "AvatarUniqueEffect",
            "BuildDepth",
            "CanBeDropped",
            "CanBeSold",
            "ClearUndoHistoryOnActivate",
            "Clickable",
            "Consumed",
            "CooldownShowDisabledDuration",
            "Description",
            "DisabledDescriptionOverride",
            "DisappersOnDeath",
            "DisplayName",
            "DropsOnDeath",
            "DynamicTooltip",
            *[ "Effect%dAmount" % x for x in range(0, 16) ],
            "EffectRadius",
            "Epicness",
            "FlatArmorMod",
            "FlatArmorPenetrationMod",
            "FlatAttackRangeMod",
            "FlatAttackSpeedMod",
            "FlatBlockMod",
            "FlatBubbleRadius",
            "FlatCastRangeMod",
            "FlatCooldownMod",
            "FlatCritChanceMod",
            "FlatCritDamageMod",
            "FlatDodgeMod",
            "FlatEnergyPoolMod",
            "FlatEnergyRegenMod",
            "FlatEXPBonus",
            "FlatHPPoolMod",
            "FlatHPRegenMod",
            "FlatMagicDamageMod",
            "FlatMagicPenetrationMod",
            "FlatMagicPenetrationModPerLevel",
            "FlatMagicReduction",
            "FlatMissChanceMod",
            "FlatMovementSpeedMod",
            "FlatPhysicalDamageMod",
            "FlatPhysicalReduction",
            "FlatSpellBlockMod",
            "ForceLoad",
            "HideFromAll",
            "ImagePath",
            "InStore",
            "InventoryIcon",
            "InventorySlotMax",
            "InventorySlotMin",
            "IsRecipe",
            "ItemCalloutPlayer",
            "ItemCalloutSpectator",
            "ItemClass",
            "ItemGroup",
            "ItemId",
            "ItemType",
            "ItemVOGroup",
            "MaxGroupOwnable",
            "MaxStack",
            "PARStatName",
            "PercentArmorMod",
            "PercentArmorPenetrationMod",
            "PercentAttackRangeMod",
            "PercentAttackSpeedMod",
            "PercentBaseHPRegenMod",
            "PercentBaseMPRegenMod",
            "PercentBlockMod",
            "PercentBonusArmorPenetrationMod",
            "PercentBonusMagicPenetrationMod",
            "PercentBubbleRadius",
            "PercentCastRangeMod",
            "PercentCooldownMod",
            "PercentCritChanceMod",
            "PercentCritDamageMod",
            "PercentDodgeMod",
            "PercentEXPBonus",
            "PercentHardnessMod",
            "PercentHealingAmountMod",
            "PercentHPPoolMod",
            "PercentHPRegenMod",
            "PercentLifeStealMod",
            "PercentMagicDamageMod",
            "PercentMagicPenetrationMod",
            "PercentMagicReduction",
            "PercentMovementSpeedMod",
            "PercentMultiplicativeAttackSpeedMod",
            "PercentMultiplicativeMovementSpeedMod",
            "PercentPhysicalDamageMod",
            "PercentPhysicalReduction",
            "PercentSlowResistMod",
            "PercentSpellBlockMod",
            "PercentSpellEffectivenessMod",
            "PercentSpellVampMod",
            "PercentTenacityCharacterMod",
            "PercentTenacityCleanseMod",
            "PercentTenacityItemMod",
            "PercentTenacityMasteryMod",
            "PercentTenacityRuneMod",
            "PlatformEnabled",
            "Price",
            "PurchaseCooldown",
            *[ "RecipeItem%d" % x for x in range(0, 10) ],
            "RequiredChampion",
            *[ "RequiredItem%d" % x for x in range(0, 10) ],
            "RequiredLevel",
            "RequiredSpellName",
            "rFlatArmorModPerLevel",
            "rFlatArmorPenetrationMod",
            "rFlatArmorPenetrationModPerLevel",
            "rFlatCritChanceModPerLevel",
            "rFlatCritDamageModPerLevel",
            "rFlatDodgeMod",
            "rFlatDodgeModPerLevel",
            "rFlatEnergyModPerLevel",
            "rFlatEnergyRegenModPerLevel",
            "rFlatGoldPer10Mod",
            "rFlatHPModPerLevel",
            "rFlatHPRegenModPerLevel",
            "rFlatMagicDamageModPerLevel",
            "rFlatMagicPenetrationMod",
            "rFlatMagicPenetrationModPerLevel",
            "rFlatMovementSpeedModPerLevel",
            "rFlatPhysicalDamageModPerLevel",
            "rFlatSpellBlockModPerLevel",
            "rFlatTimeDeadMod",
            "rFlatTimeDeadModPerLevel",
            "rPercentArmorPenetrationMod",
            "rPercentArmorPenetrationModPerLevel",
            "rPercentAttackSpeedModPerLevel",
            "rPercentCooldownMod",
            "rPercentCooldownModPerLevel",
            "rPercentMagicPenetrationMod",
            "rPercentMagicPenetrationModPerLevel",
            "rPercentMovementSpeedModPerLevel",
            "rPercentTimeDeadMod",
            "rPercentTimeDeadModPerLevel",
            * [ "Sidegrade%d" % x for x in range(1, 5) ],
            "SidegradeCredit",
            "SellBackModifier",
            "ShowInActiveItemDisplay",
            "SpecialRecipe",
            "SpellName",
            "SpellLevel",
            "SpellCharges",
            "UsableInStore",
            "UseEffect",
            "UseWhenAcquired",
            *[ stat % par for stat in [
                    "Flat%sPoolMod",
                    "Percent%sPoolMod",
                    "Flat%sRegenMod",
                    "Percent%sRegenMod",
                    "rFlat%sModPerLevel",
                    "rFlat%sRegenModPerLevel",
                ] for par in all_stats
            ],
        ],
    ],
    [
        [ "Movement", ],
        [
            "Boots",
            "NonbootsMovement",
        ],
    ],
    [ 
        [ "Start", ],
        [
            "Jungle", 
            "Lane",
        ],
    ],
    [
        [ "Defense", ],
        [
            "Armor",
            "Health",
            "HealthRegen",
            "SpellBlock",
            "Tenacity",
        ],
    ],
    [
        [ "Magic", ],
        [
            "SpellVamp",
            "Mana",
            "ManaRegen",
            "CooldownReduction",
            "SpellDamage",
        ],
    ],
# DATA/Spells/X.inibin, 
# DATA/Shared/Spells/X.inibin, 
# DATA/Characters/Y/Spells/X.inibin,
# DATA/Talents/X.inibin
    [
        [ "SpawningUI", ],
        [
            "BuffNameFilter",
            "MaxNumberOfUnits",
        ],
    ],
    [
        [ "Data", ],
        [
            "Cooldown",
            *[ "Level%dDesc" % x for x in range(1, 6) ],
            *[ "ManaCost%d" % x for x in range(1, 6) ],
            "Range",
            "SpellDelayCastTime",
            "SpellDelayTotalTime",
        ],
    ],
    [
        [ "SpellData", ],
        [
            "AfterEffectName",
            "AIBlockLevel",
            "AIEndOnly",
            "AILifetime",
            "AIRadius",
            "AIRange",
            "AISendEvent",
            "AISpeed",
            "AllowWhileTaunted",
            "AlternateName",
            "AlwaysSnapFacing",
            "AmmoCountHiddenInUI",
            "AmmoNotAffectedByCDR",
            "AmmoRechargeTime",
            *[ "AmmoRechargeTime%d" % x for x in range(1, 7) ],
            "AmmoUsed",
            *[ "AmmoUsed%d" % x for x in range(1, 7) ],
            "AnimationLeadOutName",
            "AnimationLoopName",
            "AnimationName",
            "AnimationWinddownName",
            "ApplyAttackDamage",
            "ApplyAttackEffect",
            "ApplyMaterialOnHitSound",
            "AttackDelayCastOffsetPercent",
            "BelongsToAvatar",
            "BounceRadius",
            "CanCastWhileDisabled",
            "CancelChargeOnRecastTime",
            "CanMoveWhileChanneling",
            "CannotBeSuppressed",
            "CanOnlyCastWhileDead",
            "CanOnlyCastWhileDisabled",
            "CantCancelWhileChanneling",
            "CantCancelWhileWindingUp",
            "CantCastWhileRooted",
            "CastConeAngle",
            "CastConeDistance",
            "CastFrame",
            *map_vars("CastRadius"),
            *map_vars(*[ "CastRadius%d" % x for x in range(0, 7) ]),
            *map_vars("CastRadiusSecondary"),
            *map_vars(*[ "CastRadiusSecondary%d" % x for x in range(0, 7) ]),
            "CastRadiusSecondaryTexture",
            "CastRadiusTexture",
            *map_vars("CastRange"),
            *map_vars(*[ "CastRange%d" % x for x in range(0, 7) ]),
            *map_vars("CastRangeDisplayOverride"),
            *map_vars(*[ "CastRangeDisplayOverride%d" % x for x in range(0, 7) ]),
            "CastRangeGrowthDuration",
            *[ "CastRangeGrowthDuration%d" % x for x in range(0, 7) ],
            "CastRangeGrowthMax",
            *[ "CastRangeGrowthMax%d" % x for x in range(0, 7) ],
            "CastRangeTextureOverrideName",
            "CastRangeUseBoundingBoxes",
            "CastRangeUseMapScaling",
            "CastTargetAdditionalUnitsRadius",
            "CastType",
            "ChannelDuration",
            *[ "ChannelDuration%d" % x for x in range(0, 7) ],
            "ChargeUpdateInterval",
            "CircleMissileAngularVelocity",
            "CircleMissileRadialVelocity",
            "ClientOnlyMissileTargetBoneName",
            "Coefficient",
            "Coefficient2",
            "ConsideredAsAutoAttack",
            *map_vars("Cooldown"),
            *map_vars(*[ "Cooldown%d" % x for x in range(0, 7) ]),
            "CursorChangesInGrass",
            "CursorChangesInTerrain",
            "DeathRecap",
            "DeathRecapPriority",
            "DelayCastOffsetPercent",
            "DelayTotalTimePercent",
            "Description",
            "DisableCastBar",
            "DisplayName",
            "DoesntBreakChannels",
            "DoNotNeedToFaceTarget",
            "DrawSecondaryLineIndicator",
            "DynamicExtended",
            "DynamicTooltip",
            *map_vars(*[ "Effect%dLevel%dAmount" % (x, y) for x in range(0, 17) for y in range(0, 7) ]),
            "ExcludedUnitTags",
            "Flags",
            *[ "FloatStaticsDecimals%d" % x for x in range(1, 7) ],
            *[ "FloatVarsDecimals%d" % x for x in range(1, 7) ],
            "HaveAfterEffect",
            "HaveHitBone",
            "HaveHitEffect",
            "HavePointEffect",
            "HideRangeIndicatorWhenCasting",
            "HitBoneName",
            "HitEffectName",
            "HitEffectOrientType",
            "HitEffectPlayerName",
            "IgnoreAnimContinueUntilCastFrame",
            "IgnoreRangeCheck",
            "InventoryIcon",
            "InventoryIcon1",
            "InventoryIcon2",
            "InventoryIcon3",
            "IsDisabledWhileDead",
            "IsToggleSpell",
            "KeywordWhenAcquired",
            *[ "Level%dDesc" % x for x in range(0, 7) ],
            "LineDragLength",
            "LineMissileBounces",
            "LineMissileCollisionFromStartPoint",
            "LineMissileDelayDestroyAtEndSeconds",
            "LineMissileEndsAtTargetPoint",
            "LineMissileFollowsTerrainHeight",
            "LineMissileTargetHeightAugment",
            "LineMissileTimePulseBetweenCollisionSpellHits",
            "LineMissileTrackUnits",
            "LineMissileTrackUnitsAndContinues",
            "LineMissileUsesAccelerationForBounce",
            "LineTargetingBaseTextureOverrideName",
            "LineTargetingTargetTextureOverrideName",
            "LineWidth",
            *[ "LocationTargettingLength%d" % x for x in range(0, 8) ],
            *[ "LocationTargettingWidth%d" % x for x in range(0, 8) ],
            "LockConeToPlayer",
            "LookAtPolicy",
            "LuaOnMissileUpdateDistanceInterval",
            "ManaCost",
            *[ "ManaCost%d" % x for x in range(1, 8) ],
            "MaxAmmo",
            *[ "MaxAmmo%d" % x for x in range(1, 8) ],
            "MaxGrowthRangeTextureName",
            "MaxGrowthLineBaseTextureName",
            "MaxGrowthLineTargetTextureName",
            "MaxHighlightTargets",
            "MinimapIcon",
            "MinimapIconDisplayFlag",
            "MinimapIconRotation",
            "MissileAccel",
            "MissileBoneName",
            "MissileBlockTriggersOnDestroy",
            "MissileEffect",
            "MissileEffectEnemy",
            "MissileEffectPlayer",
            "MissileFixedTravelTime",
            "MissileFollowsTerrainHeight",
            "MissileGravity",
            "MissileLifetime",
            "MissileMaxSpeed",
            "MissileMinSpeed",
            "MissileMinTravelTime",
            "MissilePerceptionBubbleRadius",
            "MissilePerceptionBubbleRevealsStealth",
            "MissileSpeed",
            "MissileTargetHeightAugment",
            "MissileUnblockable",
            "Name",
            "NoWinddownIfCancelled",
            "NumSpellTargeters",
            "OrientRadiusTextureFromPlayer",
            "OrientRangeIndicatorToCursor",
            "OrientRangeIndicatorToFacing",
            "OverrideForceSpellAnimation",
            "OverrideForceSpellCancel",
            "OverrideCastTime",
            "ParticleStartOffset",
            "PhysicalDamageRatio",
            "PlatformEnabled",
            "PointEffectName",
            "PreventChargingSecondCast",
            "Ranks",
            "RangeIndicatorTextureName",
            "RequiredUnitTags",
            "ShowInTrackerUI",
            "SelectionPreference",
            "Sound_CastName",
            "Sound_HitName",
            "Sound_VOEventCategory",
            "SpellCastTime",
            "SpellDamageRatio",
            "SpellRevealsChampion",
            "SpellTotalTime",
            "StartCooldown",
            "SubjectToGlobalCooldown",
            "TargeterConstrainedToRange",
            "TargettingType",
            "TextFlags",
            "TriggersGlobalCooldown",
            "UpdateRotationWhenCasting",
            "UseAnimatorFramerate",
            "UseAutoattackCastTime",
            "UseChargeChanneling",
            "UseChargeTargeting",
            "UseGlobalLineIndicator",
            "UseMinimapTargeting",
            "Version",
            "x1",
            "x2",
            "x3",
            "x4",
            "x5",
        ],
    ],
    [
        [ "OffsetTargeting", ],
        [
            "OT_ArcTextureOverride",
            "OT_ArcThicknessOffset",
            "OT_AreaRadius",
            "OT_AreaRadius1",
            "OT_AreaRadius2",
            "OT_AreaRadius3",
            "OT_AreaRadius4",
            "OT_AreaRadius5",
            "OT_AreaTextureOverride",
            "OT_DisplaysArcTargeter",
            "OT_DisplaysAreaIndicator",
            "OT_DisplaysLineIndicator",
            "OT_IsArcDirectionLeft",
            "OT_LineBaseTextureOverride",
            "OT_LineEndsAtTargetPoint",
            "OT_LineLength",
            "OT_LineLength1",
            "OT_LineLength2",
            "OT_LineLength3",
            "OT_LineLength4",
            "OT_LineLength5",
            "OT_LineNoIndicatorRadiusTextureOverride",
            "OT_LineTargetTextureOverride",
            "OT_LineWidth",
        ],
    ],
    [
        [ "SecondaryTargeting", ],
        [
            "CastRadius",
            "CastRadiusTexture",
            *map_vars("CastRange"),
            *map_vars(*[ "CastRange%d" % x for x in range(1, 8) ]),
            "CastRangeGrowthMax",
            *[ "CastRangeGrowthMax%d" % x for x in range(1, 8) ],
            "CastRangeGrowthDuration",
            *[ "CastRangeGrowthDuration%d" % x for x in range(1, 8) ],
            "LineTargetingBaseTextureOverrideName",
            "LineTargetingTargetTextureOverrideName",
            "LineWidth",
            *[ "LocationTargettingWidth%d" % x for x in range(1, 7) ],
            *[ "LocationTargettingLength%d" % x for x in range(1, 7) ],
            "TargettingType",
        ],
    ],
    [
        [ *["SpellTargeter%d" % x for x in range(0, 9)], ],
        [
            *[ "%s%s" % (x,y) for x in [
                    "ConstraintPos",
                    "Center",
                    "End",
                    "Start",
                ] for y in [
                    "_AngleOffset",
                    "_BasePosition",
                    "_DistanceOffset",
                    "_OrientationType",
                ]
            ],
            "AlternateName",
            "AlwaysDraw",
            *[ "CastRange%d" % x for x in range(0, 7) ],
            "Center",
            "ConeAngle",
            "ConeRange",
            "ConeFollowsEnd",
            "ConstraintPos",
            "ConstraintRange",
            "DrawableType",
            "End",
            "FallbackDirection",
            "HasMaxGrowRangeTexture",
            "HideWithLineIndicator",
            "IsConstrainedToRange",
            "IsClockwiseArc",
            "Length",
            *[ "Length%d" % x for x in range(0,7) ],
            "LineMissileCollisionFromStartPoint",
            "LineMissileDelayDestroyAtEndSeconds",
            "LineMissileEndsAtTargetPoint",
            "LineMissileTimePulseBetweenCollisionSpellHits",
            "LineMissileTrackUnits",
            "LineStopsAtEndPosition",
            "LineTargetingTargetTextureOverrideName",
            "LineTargetingBaseTextureOverrideName",
            "LineWidth",
            "MaxAngle",
            "MaxAngleRangeFactor",
            "MinAngle",
            "MinAngleRangeFactor",
            "MinimumDisplayedRange",
            "MissilePerceptionBubbleRadius",
            "MissilePerceptionBubbleRevealsStealth",
            "OverrideBaseRange",
            *[ "OverrideBaseRange%d" % x for x in range(0,7) ],
            "OverrideForceSpellAnimation",
            "OverrideForceSpellCancel",
            "OverrideRadius",
            *[ "OverrideRadius%d" % x for x in range(0,7) ],
            "Range",
            "RangeGrowthDuration",
            *[ "RangeGrowthDuration%d" % x for x in range(0,7) ],
            "RangeGrowthMax",
            *[ "RangeGrowthMax%d" % x for x in range(0,7) ],
            "RangeIndicatorTextureName",
            "SpellRevealsChampion",
            "Start",
            "TargettingType",
            "TextureBaseMaxGrow",
            "TextureBaseOverride",
            "TextureCone",
            "TextureConeMaxGrow",
            "TextureMaxGrow",
            "TextureOrientation",
            "TextureOverride",
            "TextureTargetMaxGrow",
            "TextureTargetOverride",
            "TextureWall",
            "Thickness",
            *[ "Thickness%d" % x for x in range(0,7) ],
            "ThicknessOffset",
            "UseCasterBoundingBox",
            "UseGlobalLineIndicator",
            "UseMinimapTargeting",
            "WallOrientation",
            "WallRotation",
        ],
    ],
# DATA/Characters/X/X.inibin
# DATA/Characters/Y/Skins/X/X.inibin
    [
        [ "System", ],
        [
            "Enabled", 
        ],
    ],
    [
        [ "HealthBar", ],
        [
            "ShowTicks", 
        ],
    ],
    [
        [ "ContextualAction", ],
        [
            "RuleConfigFile",
            "UsesSkinVO",
        ],
    ],
    [
        [ "Data", ],
        [
            "AbilityPowerIncPerLevel",
            "AcquisitionRange",
            "AllowPetControl",
            "AlwaysVisible",
            *map_vars("Armor"),
            "ArmorMaterial",
            *map_vars("ArmorPerLevel"),
            "AssetCategory",
            "AttackAutoInterruptPercent",
            "AttackCastTime",
            "AttackDelayCastOffsetPercent",
            "AttackDelayCastOffsetPercentAttackSpeedRatio",
            "AttackDelayOffsetPercent",
            "AttackRange",
            "AttackRank",
            "AttackSpeed",
            "AttackSpeedPerLevel",
            "AttackTotalTime",
            "BaseAbilityPower",
            "BaseCritChance",
            "BaseDamage",
            "BaseDodge",
            *map_vars("BaseFactorHPRegen"),
            *map_vars("BaseFactorMPRegen"),
            *map_vars("BaseHP"),
            *map_vars("BaseMP"),
            "BaseMissChance",
            "BaseSpellEffectiveness",
            *map_vars("BaseStaticHPRegen"),
            *map_vars("BaseStaticMPRegen"),
            "BotEnabled",
            "BotEnabledMM",
            "CastShadows",
            "ChampionId",
            "CharAudioNameOverride",
            "ChasingAttackRangePercent",
            "Classification",
            "CritDamageBonus",
            "CritPerLevel",
            "CS_easy",
            "CS_medium",
            "CS_hard",
            "DamagePerLevel",
            "DeathEventListeningRadius",
            "DeathTime",
            "DefenseRank",
            "DelayCastOffsetPercent",
            "DelayTotalTimePercent",
            "Description",
            "DifficultyRank",
            "DisableAggroIndicator",
            "DisableContinuousTargetFacing",
            "DisableGlobalDeathEffect",
            "DisableUltReadySounds",
            "DodgePerLevel",
            "DrawPARLikeHealth",
            "EnemyTooltip",
            "ExperienceRadius",
            "ExpGivenOnDeath",
            *[ v % (a, x if x > 0 else  "") for a in [
                    "BaseAttack",
                    "BasicAttack",
                    "ExtraAttack",
                    "CritAttack",
                    "ExtraCritAttack",
                    "CriticalAttack",
                ] for v  in [
                    "%s%s",
                    "%s%s_AttackCastTime",
                    "%s%s_AttackCastDelayOffsetPercent",
                    "%s%s_AttackDelayCastOffsetPercent",
                    "%s%s_AttackDelayCastOffsetPercentAttackSpeedRatio",
                    "%s%s_AttackDelayOffsetPercent",
                    "%s%s_AttackTotalTime",
                    "%s%s_Probability",
                ] for x in range(0, 10)
            ],
            *[ "ExtraSpell%d" % x for x in range(0, 17) ],
            "FireworksEnabled",
            "FriendlyTooltip",
            "GameplayCollisionRadius",
            "GlobalExpGivenOnDeath",
            "GlobalGoldGivenOnDeath",
            "GoldGivenOnDeath",
            "GoldRadius",
            "HitFxScale",
            "HoverIndicatorRadius",
            "HoverIndicatorTextureName",
            "HoverLineIndicatorBaseTextureName",
            "HoverLineIndicatorTargetTextureName",
            "HoverLineIndicatorWidth",
            "HPPerLevel",
            "HPRegenPerLevel",
            "Immobile",
            "IsElite",
            "IsEpic",
            "IsImportantBotTarget",
            "IsMelee",
            "JointForAnimAdjustedSelection",
            "LevelDodge",
            "LevelSpellEffectiveness",
            "LocalExpGivenOnDeath",
            "LocalGoldGivenOnDeath",
            "LocalGoldSplitWithLastHitter",
            "Lore1",
            "Lore2",
            "MagicRank",
            "MaxLevels",
            "Metadata",
            "MonsterDataTableId",
            "MoveSpeed",
            "MPPerLevel",
            "MPRegenPerLevel",
            "Name",
            "NeverRender",
            "NoAutoAttack",
            "NoHealthBar",
            "OccludedUnitSelectableDistance",
            "OutlineBBoxExpansion",
            "PARColor",
            "PARDisplayThroughDeath",
            "PARFadeColor",
            "PARHasRegenText",
            "PARIncrements",
            "PARMaxSegments",
            "PARNameString",
            "PARType",
            *[ p % x for x in range(1, 7) for p in [
                    "Passive%d",
                    "Passive%dDesc",
                    *[ "PassLev%%dDesc%d" % y for y in range(0,7) ],
                    "Passive%dIcon",
                    *[ "Passive%%dLevel%d" % y for y in range(0,7) ],
                    *[ "Passive%%dEffect%d" % y for y in range(0,7) ],
                    "Passive%dLuaName",
                    "Passive%dName",
                    "Passive%dNumEffects",
                    "Passive%dRange",
                ]
            ],
            "PassiveSpell",
            "PathfindingCollisionRadius",
            "PerceptionBubbleRadius",
            "PlatformEnabled",
            "PostAttackMoveDelay",
            "RecordAsWard",
            "Roles",
            "SearchTags",
            "SelectionHeight",
            "SelectionRadius",
            "SequentialAutoAttacks",
            "ServerOnly",
            "ShouldFaceTarget",
            "Significance",
            "SkipDrawOutline",
            "SkipDrawToonInking",
            "SoulGivenOnDeath",
            *[ s % x for x in range(1, 5) for s in [
                    "Spell%d",
                    "Spell%dDesc",
                    "Spell%dDisplayName",
                    "SpellsUpLevels%d",
                ]
            ],
            *map_vars("SpellBlock"),
            *map_vars("SpellBlockPerLevel"),
            "SR_easy",
            "SR_medium",
            "SR_hard",
            "Tips1",
            "Tips2",
            "Tips3",
            "TowerTargetingPriorityBoost",
            "TriggersOrderAcknowledgementVO",
            "UnitTags",
            "UseChampionVisibility",
            "UseRingIconForKillCallout",
            "WeaponMaterial",
            "`WeaponMaterial",
            "WeaponMaterial1",
            "WeaponMaterial2",
            "WeaponMaterial3",
            "WeaponMaterial4",
        ],
    ],
    [
        [ "DefaultAnimations", ],
        [
            *[ "Animation%d" % x for x in range(1, 10) ],
            "NumberOfAnimations",
            "Significance",
        ],
    ],
    [
        [ "Evolution", ],
        [
            "EnabledWhileDead",
            "EvolveTitle",
            "Spell1EvolveDesc",
            "Spell1EvolveIcon",
            "Spell2EvolveDesc",
            "Spell2EvolveIcon",
            "Spell3EvolveDesc",
            "Spell3EvolveIcon",
            "Spell4EvolveDesc",
            "Spell4EvolveIcon",
        ],
    ],
    [
        [ "HealthBar", ],
        [
            "AttachToBone",
            "HPPerTick",
            "ParallaxOffset",
            "Scale",
            "ShowWhileUntargetable",
            "UnitBarKey",
            "WorldOffset",
            "XOffset",
            "YOffset",
        ],
    ],
    [
        [ "IdleParticles", ],
        [
            "BeamParticle",
            "BeamShouldAlwayStargetEnemy",
            "BeamTargetParticle",
            "ChampTargetingParticle",
            "GameplayCollisionRadius",
            "NumberOfParticles",
            "SelfIllumination",
            *[ "Particle%d" % x for x in range(0, 100) ],
            "TowerTargetingParticle",
            "TowerTargetingParticle2",
            "TowerTargetingParticle2Death",
        ],
    ],
    [
        [ 
            "Info",
            *[ "Info%d" % x for x in range(1, 8) ],
        ],
        [
            "IconCircle",
            "IconCircleScale",
            "IconMinimap",
            "IconSquare",
        ],
    ],
    [
        [ "Interaction" ],
        [
            "DoubleSided",
            "IdleAnim",
            "RandomizeIdleAnimPhase",
        ],
    ],
    [ 
        [ "MeshSkin", ],
        [
            *[ "Attack%d" % x for x in range(1, 5) ],
            *[ "Click%d" % x for x in range(1, 5) ],
            "Death",
            *[ "Move%d" % x for x in range(1, 5) ],
            "SkinClassification",
            *[ "Special%d" % x for x in range(1, 5) ],
        ],
    ],
    [
        [ 
            "MeshSkin",
            *[ "MeshSkin%d" % x for x in range(1, 30) ],
        ],
        [
            "Animations",
            "ArmorMaterial",
            "AttributeFlags",
            "Body",
            "BrushAlphaOverride",
            "CastShadows",
            "ChampionSkinID",
            "ChampionSkinName",
            "DisablePreload",
            "EmissiveTexture",
            "ExtraCharacterPreloads",
            "Fresnel",
            "FresnelBlue",
            "FresnelGreen",
            "FresnelRed",
            "GameplayCollisionRadius",
            "GlossTexture",
            "GlowFactor",
            "HPPerTick",
            "IconAvatar",
            "IsOpaque",
            *[ mat % x for x in range(0,5) for mat in [
                    "MaterialOverride%dBlendMode",
                    "MaterialOverride%dGlossTexture",
                    "MaterialOverride%dEmissiveTexture",
                    "MaterialOverride%dFixedAlphaScrolling",
                    "MaterialOverride%dPriority",
                    "MaterialOverride%dRenderingMode",
                    "MaterialOverride%dSubMesh",
                    "MaterialOverride%dTexture",
                    "MaterialOverride%dUVScroll",
                ]
            ],
            "MaterialOverrideTransMap",
            "MaterialOverrideTransSource",
            "MaterialOverridePriority",
            "MaxNumBlendWeights",
            "Metadata",
            "OverrideBoundingBox",
            "ParallaxOffset",
            "ParticleOverride_ChampionKillDeathParticle",
            "ParticleOverride_DeathParticle",
            "Ready",
            "ReflectionFresnel",
            "ReflectionFresnelBlue",
            "ReflectionFresnelGreen",
            "ReflectionFresnelRed",
            "ReflectionMap",
            "ReflectionOpacityDirect",
            "ReflectionOpacityGlancing",
            "Scale",
            "SelfIllumination",
            "SimpleSkin",
            "Skeleton",
            "SkinScale",
            "SkinAudioNameOverride",
            "SkipVOOverride",
            "SubmeshMouseOversToHide",
            "SubmeshesToHide",
            "SubmeshShadowsToHide",
            "Texture",
            "TextureLow",
            "UseChildAnimationOverride",
            "UsesSkinVO",
            "UnitBarKey",
            "VOOverride",
            "Weight",
            "WorldOffset",
            "XOffset",
            "YOffset",
        ],
    ],
    [
        [ "Minimap", ],
        [
            "MinimapIconOverride",
        ],
    ],
    [
        [ "Minion", ],
        [
            "AlwaysUpdatePAR",
            "AlwaysVisible",
            "IsTower",
        ],
    ],
    [
        [ "Package", ],
        [
            "FallbackPackage",
            "FallbackINI",
        ],
    ],
    [
        [ 
            "ItemSet1",
            "ItemSet2",
            "RecItems",
            "TutorialRecItems",
        ],
        [
            "SetName",
            *[ "RecItem%d" % x for x in range(1, 7) ],
        ],
    ],
    [
        [ "Sounds", ],
        [
            "Attack1",
            "Attack2",
            "Attack3",
            "Attack4",
            "Click1",
            "Click2",
            "Click3",
            "Click4",
            "Death",
            "Move1",
            "Move2",
            "Move3",
            "Move4",
            "Ready",
            "Special1",
            "Special2",
        ],
    ],
    [
        [ "Useable", ],
        [
            "AllyCanUse",
            "CooldownSpellSlot",
            "EnemyCanUse",
            "GoldRedirectTargetUseableOnly",
            "HeroUseSpell",
            "IsUseable",
            "MinionUseable",
            "MinionUseSpell",
        ],
    ],
    [
        [ "Shader", ],
        [
            "HasTangent",
            "Pixel",
            "Vertex",
        ],
    ],
]

all_inibin_fixdict = {
    h: (s, n) for sn in all_inibin_fixlist for s,n,h in a_ihash(*sn)
}

def verify_fixdict():
    results = {}
    for sn in all_inibin_fixlist:
        for s,n,h in a_ihash(*sn):
            if h in results:
                s1, n1 = results[h][0].lower(), results[h][1].lower()
                s2, n2 = s.lower(), n.lower()
                if (s1,n1) != (s2, n2):
                    raise ValueError(f"Collision: {s1}*{n1} vs {s2}*{n2}")
            else:
                results[h] = (s,n)
    

def get_fixdict(inib = None):
    return all_inibin_fixdict

# unhashes .inibin with dictionary
def fix(inib, fixd = None):
    if fixd == None:
        fixd = get_fixdict(inib)
    if not "Values" in inib:
        inib["Values"] = {}
    if not "UNKNOWN_HASHES" in inib:
        inib["UNKNOWN_HASHES"] = {}
    values = inib["Values"]
    inib["UNKNOWN_HASHES"] = { int(k): v for k,v in inib["UNKNOWN_HASHES"].items() }
    unk = inib["UNKNOWN_HASHES"]

    for h, (s, n) in fixd.items():
        if h in unk:
            if not s in values:
                values[s] = {}
            values[s][n] = unk[h]
            del unk[h]
    
def fix_dry(inib, fixd = None):
    if fixd == None:
        fixd = get_fixdict(inib)
    return len(inib["UNKNOWN_HASHES"]), len((
        *(h for h in inib["UNKNOWN_HASHES"] if h in fixd),
    ))
