#!/usr/bin/env python
from sys import stderr
COMMENTS=("%s", "'%s")

def ihash(value, ret = 0):
    for c in value:
        ret = (ord(c.lower()) +((65599 * ret) & 0xffffffff)) & 0xffffffff
    return ret

def a_ihash(sections, names):
    for section in sections:
        sectionhash = ihash('*', ihash(section))
        for rawname in names:
            for com in COMMENTS:
                name = com % rawname
                ret = ihash(name, sectionhash)
                yield section, name, ret

def s_n(s, *names):
    return [ [s], [*names], ]

all_gamemodes = [
    "ARAM",
    "CLASSIC",
    "FIRSTBLOOD",
    "ODIN",
    "ONEFORALL",
    "TUTORIAL",
    "ASCENSION",
    "URF",
]
all_mutators = [
    *all_gamemodes,
    "NightmareBots",
]

def map_vars(*args):
    return [
        *args,
        *[ "Map%d_%s" % (x,a) for a in args for x in range(0, 15) ],
    ]


all_inibin_fixlist = [
# LEVELS/MapX/DeathTimes.inibin
    [
        [ "DeathTimeScaling" ],
        [
            "IncrementTime",
            "PercentCap",
            "PercentIncrease",
            "StartTime",
        ]
    ],
    [
        [ "DeathTimeSettings" ], 
        [
            "AllowDeathTimeMods",
            "StartDeathTimerForZombies",
        ]
    ],
    [
        [ "DeathWaveRespawn" ], 
        [
            "WaveRespawnInterval",
        ]
    ],
    [
        [ "ExpGrantedOnDeath" ], 
        [
            "BaseExpMultiple",
            "LevelDifferenceExpMultiple",
            "MinimumExpMultiple",
        ]
    ],
    [
        [ "TimeDeadPerLevel", "TimeDeadPerLevelTutorial" ],
        [
            *[ "Level%02d" % x for x in range(0, 31) ]
        ]  
    ],
# LEVELS/MapX/Items.inibin
    [
        [ 
            "ItemInclusionList",
            "UnpurchasableItemList",
            *[ "UnpurchasableItemList_%s" % x for x in all_mutators ],
        ],
        [
            *[ "Item%d" % x for x in range(0, 200) ]
        ]
    ],
# LEVELS/MapX/NeutralTimers.inibin
    [
        [ "General" ],
        [ 
            *[ "Element%d" % x for x in range(0, 10) ],
            *[ "Element%d_%s" % (x, y) for x in range(0, 10) for y in [
                    "Default",
                    "Colorblind",
                    "Spectator",
                ]
            ],
            "HudFrameHandle",
            "HudGroup",
            "RespawnTime",
            "TimerTooltip",
            "TimerWarningThreshold",
        ],
    ],
    [
        [
            *[ "Timer%d" % x for x in range(0, 10) ]
        ],
        [
            "HudHandleText",
            "HudHandleIcon",
            *[ "HudHandleIcon_%s" % x for x in [
                    "Default",
                    "Colorblind",
                    "Spectator",
                ]
            ],
            "TimerType",
            "TooltipName",
            "TooltipRespawn",
            "TimerWarningThreshold",
        ]
    ],
# LEVELS/MapX/ExpCurve.inibin
    [
        [ "EXP", "EXPTutorial" ], 
        [
            *[ "Level{}".format(x) for x in range(0, 31) ]
        ]
    ],
# LEVELS/MapX/ExpCurve.inibin
    [
        [ "Experience", ],
        [ 
            * [ "PlayerMinionSplitXP%d" % x \
                for x in range(1, 6) 
            ],
        ],
    ],
    [
        [ "BehaviorTreeMetaData", ],
        [
            "BehaviorTreeNodeLibraryCommon",
            "BehaviorTreeNodeLibraryClient",
            "BehaviorTreeNodeLibraryServer",
        ],
    ],
    [
        [ "LoadScreen", ],
        [
            "ScreenToLoad",
        ]
    ],
# LEVELS/MapX/StatsProgression.inibin
    [
        [ "PerLevelStatsFactor" ],
        [
            *[ "Level%d" % x for x in range(0, 31) ]
        ]
    ],
# LEVELS/MapX/terrain.inibin
    s_n("AlphaTest", "cut_off",),
    s_n("ColorMap", "enable",),
    [
        [ "HeightBlending", ],
        [
            "enable", 
            "layer0_scale",
            "layer1_scale",
            "layer2_scale",
            "layer3_scale",
        ],
    ],
    [
        [ "Environment" ],
        [
            "CullingDistanceOverride",
            "DevMark",
            "Lighting",
            "Renderer",
            "ShadowBlur",
            "ShadowColor",
            "UseAlphaBlend",
        ],
    ],
    [
        [ "FoW", ],
        [
            "color_red",
            "color_green",
            "color_blue",
            "upscale",
        ],
    ],
    [
        [ "Fog", ],
        [
            "red",
            "green"
            "blue",
            "opacity",
            "min_height",
            "max_height",
            "min_radius",
            "max_radius",
            "min_opaque_height",
            "max_opaque_height", 
            "useOpacityMap",
            "enable",
        ],
    ],
# DATA/Globals/ABGroups.inibin
    [
        [
            "Settings",
        ],
        [
            "EnabledGroups",
        ],
    ],
# DATA/Globals/Critical.inibin
    [
        [ "Karma" ], 
        [
            *[ "Critical%d" % c for c in range(0, 201) ]
        ]
    ],
# Data/Globals/Tips.inibin
    [
        [
            "Global",
            *all_gamemodes
        ], 
        [
            "MaxViewable",
        ],
    ],
    [
        [
            "Global",
        ], 
        [
            "DialogueClosedSound",
            "DialogueOpenedSound",
            "MaxViewable",
            "TipRecievedSound",
        ],
    ],
# DATA/Globals/GameMutatorExpansions.inibin
    [
        [
            *all_mutators
        ],
        [
            *[ "Mutator%d" % x for x in range(0, 10) ],
        ],
    ],
# DATA/Globals/Bounty.inibin
    [
        [
            "Global",
            *all_gamemodes
        ], 
        [
            "AssistDeathstreakReduction",
            "AssistDurationOverride",
            "AssistGoldPerStreak",
            "AssistGoldStreakCap",
            "AssistGoldStreakStart",
            "AssistPoolMax",
            "AssistPoolMaxValueTime",
            "AssistPoolMin",
            "AssistPoolMinValueTime",
            "AssistStreakBonus",
            "AssistStreakMin",
            "BaseGold",
            "BountyRoundDownIncrement",
            "DeathStreakPenalty",
            "FirstBloodBonus",
            "GoldPoolForAssist",
            "KillStreakBonus",
            "MaxKillStreakBonus",
            "MinAssistsForStreak",
            "MinDeathsForStreak",
            "MinDeathStreakPenalty",
            "MinionGoldDeathstreakReductionRatio",
            "MinionGoldValueForBounty",
            "MinKillsForStreak",
            "MinMinionGoldValueForBounty",
            "PercentBountyResetOnDeath",
            "TimeBasedMinValuePercent",
            "TimeToMaxValueInSeconds",
            "TimeToMinValueInSeconds",
        ]
    ],
# DATA/Globals/*_Stats.inibin
    [
        [
            "HeroStats",
        ],
        [
            "ID",
            "NAME",
            "SKIN",
            "TEAM",
            "WIN",
            "EXP",
            "LEVEL",
            "GOLD_SPENT",
            "GOLD_EARNED",
            "NUM_DEATHS",
            "CHAMPIONS_KILLED",
            "ASSISTS",
            "BARRACKS_KILLED",
            "TURRETS_KILLED",
            "HQ_KILLED",
            "MINIONS_KILLED",
            "NEUTRAL_MINIONS_KILLED",
            "SUPER_MONSTER_KILLED",
            "LARGEST_KILLING_SPREE",
            "KILLING_SPREES",
            "LARGEST_MULTI_KILL",
            "TOTAL_DAMAGE_DEALT",
            "PHYSICAL_DAMAGE_DEALT_PLAYER",
            "MAGIC_DAMAGE_DEALT_PLAYER",
            "TOTAL_DAMAGE_DEALT_TO_CHAMPIONS",
            "PHYSICAL_DAMAGE_DEALT_TO_CHAMPIONS",
            "MAGIC_DAMAGE_DEALT_TO_CHAMPIONS",
            "TOTAL_DAMAGE_TAKEN",
            "PHYSICAL_DAMAGE_TAKEN",
            "MAGIC_DAMAGE_TAKEN",
            "DOUBLE_KILLS",
            "TRIPLE_KILLS",
            "QUADRA_KILLS",
            "PENTA_KILLS",
            "UNREAL_KILLS",
            "ITEMS_PURCHASED",
            "CONSUMABLES_PURCHASED",
            "SPELL1_CAST",
            "SPELL2_CAST",
            "SPELL3_CAST",
            "SPELL4_CAST",
            "SUMMON_SPELL1_CAST",
            "SUMMON_SPELL2_CAST",
            "LARGEST_CRITICAL_STRIKE",
            "TIME_PLAYED",
            "LONGEST_TIME_SPENT_LIVING",
            "TOTAL_TIME_SPENT_DEAD",
            "TOTAL_HEAL",
            "TOTAL_UNITS_HEALED",
            "FRIENDLY_TURRET_LOST",
            "FRIENDLY_DAMPEN_LOST",
            "FRIENDLY_HQ_LOST",
            "TOOK_FIRST_BLOOD",
            "WAS_AFK",
            "WAS_AFK_AFTER_FAILED_SURRENDER",
            "TIME_OF_FROM_LAST_DISCONNECT",
            "TIME_SPENT_DISCONNECTED",
            "NEVER_ENTERED_GAME",
            "TEAMMATE_NEVER_ENTERED_GAME",
            "ITEM0",
            "ITEM1",
            "ITEM2",
            "ITEM3",
            "ITEM4",
            "ITEM5",
            "ITEM6",
            "SIGHT_WARDS_BOUGHT_IN_GAME",
            "VISION_WARDS_BOUGHT_IN_GAME",
            "NODE_CAPTURE",
            "NODE_NEUTRALIZE",
            "NODE_KILL_OFFENSE",
            "TEAM_OBJECTIVE",
            "DEFEND_POINT_NEUTRALIZE",
            "NODE_KILL_DEFENSE",
            "NODE_TIME_DEFENSE",
            "LAST_STAND",
            "NODE_CAPTURE_ASSIST",
            "NODE_NEUTRALIZE_ASSIST",
            "TOTAL_PLAYER_SCORE",
            "OFFENSE_PLAYER_SCORE",
            "DEFENSE_PLAYER_SCORE",
            "COMBAT_PLAYER_SCORE",
            "OBJECTIVE_PLAYER_SCORE",
            "VICTORY_POINT_TOTAL",
            "TOTAL_SCORE_RANK",
            "PING",
            "TRUE_DAMAGE_DEALT_PLAYER",
            "TRUE_DAMAGE_TAKEN",
            "TRUE_DAMAGE_DEALT_TO_CHAMPIONS",
            "WARD_PLACED",
            "WARD_KILLED",
            "TOTAL_TIME_CROWD_CONTROL_DEALT",
            "NEUTRAL_MINIONS_KILLED",
            "NEUTRAL_MINIONS_KILLED_YOUR_JUNGLE",
            "NEUTRAL_MINIONS_KILLED_ENEMY_JUNGLE",
        ],
    ],
# DATA/Globals/Quests.inibin
    [
        [
            "PrimaryQuests", 
            "SecondaryQuests", 
            "Objectives",
        ],
        [
            *[ "%s%s" % (x, y) for x in [
                    "RecievedSound",
                    "CompletedSound",
                    "FailedSound",
                ] for y in [
                    "Effect",
                    "VO_ID",
                    "VO_Folder",
                ]
            ],
            "CompletedText",
            "FailedText",
            "MaxViewable",
            "RecievedText",
            "TitleText",
        ]
    ],
    [
        [ "Coefficients" ],
        [
            "MCoefficient",
            "NCoefficient",
        ]
    ],
# DATA/Particles/ParticlesDefault.inibin
    [
        [ "GlobalEffects" ],
        [
            "Default",
            "MinionDeath",
            "TurretDeath",
            "ChaosBarracksDamper",
            "OrderBarracksDamper",
            "ChaosBarrackDeath",
            "OrderBarrackDeath",
            "LevelUp",
            "HeroKilledByNeutral",
            "HeroKilledByHero",
            "HeroKilledByPlayer",
            "HeroKilledAssistedByPlayer",
            "HeroEnemyKilled",
            "HeroAllyKilled",
            "HeroRedKilledSpectator",
            "HeroBlueKilledSpectator",
            "HeroRespawn",
            "CursorMoveTo",
            "CursorMoveToRed",
            "CursorCast",
            "FountainHeal",
            "FocusTarget",
            "DefendTarget",
            "CommandTarget",
            "CommandGround",
            "ComeHere",
            "OMW",
            "Retreat",
            "Danger",
            "MIA",
            "GoldAcquisition",
            "MissingInstant",
            "MissingLingering",
            "StartHeroSpawn",
            "ChaosHQDeath",
            "OrderHQDeath",
            "ChampionIndicator",
            "MaxIdentifier",
            * [ "EffectName%d" % x for x in range(0, 40) ],
            * [ "FileName%d" % x for x in range(0, 40) ],
            * [ "Key%d" % x for x in  range(0, 40) ],
            * [ "State%d" % x for x in range(0, 40) ],
        ],
    ],

# DATA/Characters/HeroSpawnOffsets.inibin
    [
        [
            * [ "Chaos%d" % x for x in range(1, 7) ],
            * [ "Order%d" % x for x in range(1, 7) ],
        ],
        [
            * [ "Pos%d" % x for x in range(1, 7) ],
            * [ "Facing%d" % x for x in range(1, 7) ],
        ],
    ],
# spells, items, talents (everything is a buff -.-)
    [
        [ "BuffData" ], 
        [
            "AlternateName",
            "ApplyMaterialOnHitSound",
            "DisplayName",
            "DynamicExtended",
            "DynamicTooltip",
            "DeathRecapPriority",
            *[ "Effect%dLevel%dAmount" % (x, y) for x in range(0, 17) for y in range(0, 7) ],
            *[ "FloatStaticsDecimals%d" % x for x in range(0, 17) ],
            *[ "FloatVarsDecimals%d" % x for x in range(0, 17) ],
            "HideDurationInUI",
            "InventoryIcon",
            "ShowInTrackerUI",
            "Sound_VOEventCategory",
        ]
    ],
# DATA/Items/metadadata/categories.inibin
# DATA/Items/ItemGroups/*.inibin
# DATA/Items/X.inibin
    [
        [ "Builds" ],
        [
            *[ "Item%d" % x for x in range(0, 17) ]
        ]
    ],
    [
        [ "Categories" ],
        [
            "Active",
            "Armor",
            "ArmorPenetration",
            "AttackSpeed",
            "Aura",
            "Boots",
            "Consumable",
            "CooldownReduction",
            "CriticalStrike",
            "Damage",
            "GoldPer",
            "Health",
            "HealthRegen",
            "Jungle",
            "Internal",
            "Lane",
            "LifeSteal",
            "MagicPenetration",
            "Mana",
            "ManaRegen",
            "Movement",
            "NonbootsMovement",
            "OnHit",
            "Slow",
            "SpellBlock",
            "SpellDamage",
            "SpellVamp",
            "Stealth",
            "Tenacity",
            "Trinket",
            "Vision",
        ]
    ],
    [
        [ "Data" ], 
        [
            "AvatarUniqueEffect",
            "BuildDepth",
            "CanBeDropped",
            "CanBeSold",
            "ClearUndoHistoryOnActivate",
            "Clickable",
            "Consumed",
            "CooldownShowDisabledDuration",
            "Description",
            "DisappersOnDeath",
            "DisplayName",
            "DropsOnDeath",
            "DynamicTooltip",
            *[ "Effect%dAmount" % x for x in range(0, 16) ],
            "EffectRadius",
            "Epicness",
            "FlatArmorMod",
            "FlatArmorPenetrationMod",
            "FlatAttackRangeMod",
            "FlatAttackSpeedMod",
            "FlatBlockMod",
            "FlatBubbleRadius",
            "FlatCastRangeMod",
            "FlatCooldownMod",
            "FlatCritChanceMod",
            "FlatCritDamageMod",
            "FlatDodgeMod",
            "FlatEnergyPoolMod",
            "FlatEnergyRegenMod",
            "FlatEXPBonus",
            "FlatHPPoolMod",
            "FlatHPRegenMod",
            "FlatMagicDamageMod",
            "FlatMagicPenetrationMod",
            "FlatMagicPenetrationModPerLevel",
            "FlatMagicReduction",
            "FlatMissChanceMod",
            "FlatMovementSpeedMod",
            "FlatPhysicalDamageMod",
            "FlatPhysicalReduction",
            "FlatSpellBlockMod",
            "ForceLoad",
            "HideFromAll",
            "ImagePath",
            "InStore",
            "InventoryIcon",
            "InventorySlotMax",
            "InventorySlotMin",
            "IsRecipe",
            "ItemCalloutPlayer",
            "ItemCalloutSpectator",
            "ItemClass",
            "ItemGroup",
            "ItemId",
            "ItemType",
            "ItemVOGroup",
            "MaxGroupOwnable",
            "MaxStack",
            "PARStatName",
            "PercentArmorMod",
            "PercentArmorPenetrationMod",
            "PercentAttackRangeMod",
            "PercentAttackSpeedMod",
            "PercentBaseHPRegenMod",
            "PercentBaseMPRegenMod",
            "PercentBlockMod",
            "PercentBonusArmorPenetrationMod",
            "PercentBonusMagicPenetrationMod",
            "PercentBubbleRadius",
            "PercentCastRangeMod",
            "PercentCooldownMod",
            "PercentCritChanceMod",
            "PercentCritDamageMod",
            "PercentDodgeMod",
            "PercentEXPBonus",
            "PercentHealingAmountMod",
            "PercentHPPoolMod",
            "PercentHPRegenMod",
            "PercentLifeStealMod",
            "PercentMagicDamageMod",
            "PercentMagicPenetrationMod",
            "PercentMagicReduction",
            "PercentMovementSpeedMod",
            "PercentMultiplicativeAttackSpeedMod",
            "PercentMultiplicativeMovementSpeedMod",
            "PercentPhysicalDamageMod",
            "PercentPhysicalReduction",
            "PercentSlowResistMod",
            "PercentSpellBlockMod",
            "PercentSpellEffectivenessMod",
            "PercentSpellVampMod",
            "PercentTenacityCharacterMod",
            "PercentTenacityCleanseMod",
            "PercentTenacityItemMod",
            "PercentTenacityMasteryMod",
            "PercentTenacityRuneMod",
            "PlatformEnabled",
            "Price",
            *[ "RecipeItem%d" % x for x in range(0, 10) ],
            "RequiredChampion",
            *[ "RequiredItem%d" % x for x in range(0, 10) ],
            "RequiredLevel",
            "RequiredSpellName",
            "rFlatArmorModPerLevel",
            "rFlatArmorPenetrationMod",
            "rFlatArmorPenetrationModPerLevel",
            "rFlatCritChanceModPerLevel",
            "rFlatCritDamageModPerLevel",
            "rFlatDodgeMod",
            "rFlatDodgeModPerLevel",
            "rFlatEnergyModPerLevel",
            "rFlatEnergyRegenModPerLevel",
            "rFlatGoldPer10Mod",
            "rFlatHPModPerLevel",
            "rFlatHPRegenModPerLevel",
            "rFlatMagicDamageModPerLevel",
            "rFlatMagicPenetrationMod",
            "rFlatMagicPenetrationModPerLevel",
            "rFlatMovementSpeedModPerLevel",
            "rFlatPhysicalDamageModPerLevel",
            "rFlatSpellBlockModPerLevel",
            "rFlatTimeDeadMod",
            "rFlatTimeDeadModPerLevel",
            "rPercentArmorPenetrationMod",
            "rPercentArmorPenetrationModPerLevel",
            "rPercentAttackSpeedModPerLevel",
            "rPercentCooldownMod",
            "rPercentCooldownModPerLevel",
            "rPercentMagicPenetrationMod",
            "rPercentMagicPenetrationModPerLevel",
            "rPercentMovementSpeedModPerLevel",
            "rPercentTimeDeadMod",
            "rPercentTimeDeadModPerLevel",
            "SellBackModifier",
            "ShowInActiveItemDisplay",
            "SpecialRecipe",
            "SpellName",
            "SpellLevel",
            "SpellCharges",
            "UsableInStore",
            "UseEffect",
            "UseWhenAcquired",
            *[ stat.format(par) for stat in [
                    "Flat{}PoolMod",
                    "Percent{}PoolMod",
                    "Flat{}RegenMod",
                    "Percent{}RegenMod",
                    "rFlat{}ModPerLevel",
                    "rFlat{}RegenModPerLevel",
                ] for par in [
                    "None",
                    "MP",
                    "Energy",
                    "None",
                    "Shield",
                    "BattleFury",
                    "DragonFury",
                    "GnarFury",
                    "Rage",
                    "Heat",
                    "Ferocity",
                    "Bloodwell",
                    "Wind",
                    "Other",
                ]
            ],
        ]
    ],
# DATA/Spells/X.inibin, 
# DATA/Shared/Spells/X.inibin, 
# DATA/Characters/Y/Spells/X.inibin,
# DATa/Talents/X.inibin
    [
        [ "SpawningUI" ],
        [
            "BuffNameFilter",
            "MaxNumberOfUnits",
        ]
    ],
    [
        [ "Data", ],
        [
            "SpellDelayCastTime",
            "SpellDelayTotalTime",
        ],
    ],
    [
        [ "SpellData" ],
        [
            "AfterEffectName",
            "AIBlockLevel",
            "AIEndOnly",
            "AILifetime",
            "AIRadius",
            "AIRange",
            "AISendEvent",
            "AISpeed",
            "AlternateName",
            "AlwaysSnapFacing",
            "AmmoCountHiddenInUI",
            "AmmoNotAffectedByCDR",
            "AmmoRechargeTime",
            *[ "AmmoRechargeTime%d" % x for x in range(1, 7) ],
            "AmmoUsed",
            *[ "AmmoUsed%d" % x for x in range(1, 7) ],
            "AnimationLeadOutName",
            "AnimationLoopName",
            "AnimationName",
            "AnimationWinddownName",
            "ApplyAttackDamage",
            "ApplyAttackEffect",
            "ApplyMaterialOnHitSound",
            "AttackDelayCastOffsetPercent",
            "BelongsToAvatar",
            "BounceRadius",
            "CanCastWhileDisabled",
            "CancelChargeOnRecastTime",
            "CanMoveWhileChanneling",
            "CannotBeSuppressed",
            "CanOnlyCastWhileDead",
            "CanOnlyCastWhileDisabled",
            "CantCancelWhileChanneling",
            "CantCancelWhileWindingUp",
            "CantCastWhileRooted",
            "CastConeAngle",
            "CastConeDistance",
            "CastFrame",
            *map_vars("CastRadius"),
            *map_vars(*[ "CastRadius%d" % x for x in range(0, 7) ]),
            *map_vars("CastRadiusSecondary"),
            *map_vars(*[ "CastRadiusSecondary%d" % x for x in range(0, 7) ]),
            "CastRadiusSecondaryTexture",
            "CastRadiusTexture",
            *map_vars("CastRange"),
            *map_vars(*[ "CastRange%d" % x for x in range(0, 7) ]),
            *map_vars("CastRangeDisplayOverride"),
            *map_vars(*[ "CastRangeDisplayOverride%d" % x for x in range(0, 7) ]),
            "CastRangeGrowthDuration",
            *[ "CastRangeGrowthDuration%d" % x for x in range(0, 7) ],
            "CastRangeGrowthMax",
            *[ "CastRangeGrowthMax%d" % x for x in range(0, 7) ],
            "CastRangeTextureOverrideName",
            "CastRangeUseBoundingBoxes",
            "CastTargetAdditionalUnitsRadius",
            "CastType",
            "ChannelDuration",
            *[ "ChannelDuration%d" % x for x in range(0, 7) ],
            "ChargeUpdateInterval",
            "CircleMissileAngularVelocity",
            "CircleMissileRadialVelocity",
            "ClientOnlyMissileTargetBoneName",
            "Coefficient",
            "Coefficient2",
            "ConsideredAsAutoAttack",
            *map_vars("Cooldown"),
            *map_vars(*[ "Cooldown%d" % x for x in range(0, 7) ]),
            "CursorChangesInGrass",
            "CursorChangesInTerrain",
            "DeathRecapPriority",
            "DelayCastOffsetPercent",
            "DelayTotalTimePercent",
            "Description",
            "DisableCastBar",
            "DisplayName",
            "DoesntBreakChannels",
            "DoNotNeedToFaceTarget",
            "DrawSecondaryLineIndicator",
            "DynamicExtended",
            "DynamicTooltip",
            *map_vars(*[
                "Effect%dLevel%dAmount" % (x, y) \
                    for x in range(0, 17) for y in range(0, 7)
            ]),
            "ExcludedUnitTags",
            "Flags",
            *[ "FloatStaticsDecimals%d" % x for x in range(0, 17) ],
            *[ "FloatVarsDecimals%d" % x for x in range(0, 17) ],
            "HaveAfterEffect",
            "HaveHitBone",
            "HaveHitEffect",
            "HavePointEffect",
            "HideRangeIndicatorWhenCasting",
            "HitBoneName",
            "HitEffectName",
            "HitEffectOrientType",
            "HitEffectPlayerName",
            "IgnoreAnimContinueUntilCastFrame",
            "IgnoreRangeCheck",
            "InventoryIcon",
            "InventoryIcon1",
            "InventoryIcon2",
            "InventoryIcon3",
            "IsDisabledWhileDead",
            "IsToggleSpell",
            "KeywordWhenAcquired",
            *[ "Level%dDesc" % x for x in range(0, 7) ],
            "LineDragLength",
            "LineMissileBounces",
            "LineMissileCollisionFromStartPoint",
            "LineMissileDelayDestroyAtEndSeconds",
            "LineMissileEndsAtTargetPoint",
            "LineMissileFollowsTerrainHeight",
            "LineMissileTargetHeightAugment",
            "LineMissileTimePulseBetweenCollisionSpellHits",
            "LineMissileTrackUnits",
            "LineMissileTrackUnitsAndContinues",
            "LineMissileUsesAccelerationForBounce",
            "LineTargetingBaseTextureOverrideName",
            "LineTargetingTargetTextureOverrideName",
            "LineWidth",
            *[ "LocationTargettingLength%d" % x for x in range(0, 8) ],
            *[ "LocationTargettingWidth%d" % x for x in range(0, 8) ],
            "LockConeToPlayer",
            "LookAtPolicy",
            "LuaOnMissileUpdateDistanceInterval",
            "ManaCost",
            *[ "ManaCost%d" % x for x in range(1, 8) ],
            "MaxAmmo",
            *[ "MaxAmmo%d" % x for x in range(1, 8) ],
            "MaxGrowthRangeTextureName",
            "MaxGrowthLineBaseTextureName",
            "MaxGrowthLineTargetTextureName",
            "MaxHighlightTargets",
            "MinimapIcon",
            "MinimapIconDisplayFlag",
            "MinimapIconRotation",
            "MissileAccel",
            "MissileBoneName",
            "MissileBlockTriggersOnDestroy",
            "MissileEffect",
            "MissileEffectEnemy",
            "MissileEffectPlayer",
            "MissileFixedTravelTime",
            "MissileFollowsTerrainHeight",
            "MissileGravity",
            "MissileLifetime",
            "MissileMaxSpeed",
            "MissileMinSpeed",
            "MissileMinTravelTime",
            "MissilePerceptionBubbleRadius",
            "MissilePerceptionBubbleRevealsStealth",
            "MissileSpeed",
            "MissileTargetHeightAugment",
            "MissileUnblockable",
            "Name",
            "NoWinddownIfCancelled",
            "NumSpellTargeters",
            "OrientRadiusTextureFromPlayer",
            "OrientRangeIndicatorToCursor",
            "OrientRangeIndicatorToFacing",
            "OverrideCastTime",
            "ParticleStartOffset",
            "PhysicalDamageRatio",
            "PlatformEnabled",
            "PointEffectName",
            "Ranks",
            "RangeIndicatorTextureName",
            "RequiredUnitTags",
            "SelectionPreference",
            "Sound_CastName",
            "Sound_HitName",
            "Sound_VOEventCategory",
            "SpellCastTime",
            "SpellDamageRatio",
            "SpellRevealsChampion",
            "SpellTotalTime",
            "StartCooldown",
            "SubjectToGlobalCooldown",
            "TargeterConstrainedToRange",
            "TargettingType",
            "TextFlags",
            "TriggersGlobalCooldown",
            "UpdateRotationWhenCasting",
            "UseAnimatorFramerate",
            "UseAutoattackCastTime",
            "UseChargeChanneling",
            "UseChargeTargeting",
            "UseGlobalLineIndicator",
            "UseMinimapTargeting",
            "Version",
            "x1",
            "x2",
            "x3",
            "x4",
            "x5",
        ]
    ],
    [
        [ "OffsetTargeting" ],
        [
            "OT_ArcTextureOverride",
            "OT_ArcThicknessOffset",
            "OT_AreaRadius",
            "OT_AreaRadius1",
            "OT_AreaRadius2",
            "OT_AreaRadius3",
            "OT_AreaRadius4",
            "OT_AreaRadius5",
            "OT_AreaTextureOverride",
            "OT_DisplaysArcTargeter",
            "OT_DisplaysAreaIndicator",
            "OT_DisplaysLineIndicator",
            "OT_IsArcDirectionLeft",
            "OT_LineBaseTextureOverride",
            "OT_LineEndsAtTargetPoint",
            "OT_LineLength",
            "OT_LineLength1",
            "OT_LineLength2",
            "OT_LineLength3",
            "OT_LineLength4",
            "OT_LineLength5",
            "OT_LineNoIndicatorRadiusTextureOverride",
            "OT_LineTargetTextureOverride",
            "OT_LineWidth",
        ]
    ],
    [
        [ "SecondaryTargeting" ],
        [
            "CastRadius",
            "CastRadiusTexture",
            *map_vars("CastRange"),
            *map_vars(*[ "CastRange%d" % x for x in range(1, 8) ]),
            "CastRangeGrowthMax",
            *[ "CastRangeGrowthMax%d" % x for x in range(1, 8) ],
            "CastRangeGrowthDuration",
            *[ "CastRangeGrowthDuration%d" % x for x in range(1, 8) ],
            "LineTargetingBaseTextureOverrideName",
            "LineTargetingTargetTextureOverrideName",
            "LineWidth",
            *[ "LocationTargettingWidth%d" % x for x in range(1, 7) ],
            *[ "LocationTargettingLength%d" % x for x in range(1, 7) ],
            "TargettingType",
        ]
    ],
    [
        [ *["SpellTargeter%d" % x for x in range(0, 9)] ],
        [
            *[ "%s%s" % (x,y) for x in [
                    "ConstraintPos",
                    "Center",
                    "End",
                    "Start",
                ] for y in [
                    "_AngleOffset",
                    "_BasePosition",
                    "_DistanceOffset",
                    "_OrientationType",
                ]
            ],
            "AlwaysDraw",
            "Center",
            "ConeAngle",
            "ConeRange",
            "ConeFollowsEnd",
            "ConstraintPos",
            "ConstraintRange",
            "DrawableType",
            "End",
            "FallbackDirection",
            "HasMaxGrowRangeTexture",
            "HideWithLineIndicator",
            "IsConstrainedToRange",
            "IsClockwiseArc",
            "Length",
            *[ "Length%d" % x for x in range(0,7) ],
            "LineStopsAtEndPosition",
            "LineTargetingTargetTextureOverrideName",
            "LineTargetingBaseTextureOverrideName",
            "LineWidth",
            "MaxAngle",
            "MaxAngleRangeFactor",
            "MinAngle",
            "MinAngleRangeFactor",
            "MinimumDisplayedRange",
            "OverrideBaseRange",
            *[ "OverrideBaseRange%d" % x for x in range(0,7) ],
            "OverrideRadius",
            *[ "OverrideRadius%d" % x for x in range(0,7) ],
            "RangeGrowthDuration",
            *[ "RangeGrowthDuration%d" % x for x in range(0,7) ],
            "RangeGrowthMax",
            *[ "RangeGrowthMax%d" % x for x in range(0,7) ],
            "RangeIndicatorTextureName",
            "Start",
            "TargettingType",
            "TextureBaseMaxGrow",
            "TextureBaseOverride",
            "TextureCone",
            "TextureConeMaxGrow",
            "TextureMaxGrow",
            "TextureOrientation",
            "TextureOverride",
            "TextureTargetMaxGrow",
            "TextureTargetOverride",
            "TextureWall",
            "Thickness",
            *[ "Thickness%d" % x for x in range(0,7) ],
            "ThicknessOffset",
            "UseCasterBoundingBox",
            "UseGlobalLineIndicator",
            "UseMinimapTargeting",
            "WallOrientation",
            "WallRotation",
        ]
    ],
# DATA/Characters/X/X.inibin
# DATA/Characters/Y/Skins/X/X.inibin
    [
        [ "ContextualAction" ],
        [
            "RuleConfigFile",
        ]
    ],
    [
        [ "Data" ],
        [
            "AbilityPowerIncPerLevel",
            "AcquisitionRange",
            "AllowPetControl",
            "AlwaysVisible",
            *map_vars("Armor"),
            "ArmorMaterial",
            *map_vars("ArmorPerLevel"),
            "AssetCategory",
            "AttackAutoInterruptPercent",
            "AttackCastTime",
            "AttackDelayCastOffsetPercent",
            "AttackDelayCastOffsetPercentAttackSpeedRatio",
            "AttackDelayOffsetPercent",
            "AttackRange",
            "AttackRank",
            "AttackSpeed",
            "AttackSpeedPerLevel",
            "AttackTotalTime",
            "BaseAbilityPower",
            "BaseCritChance",
            "BaseDamage",
            "BaseDodge",
            *map_vars("BaseFactorHPRegen"),
            *map_vars("BaseFactorMPRegen"),
            *map_vars("BaseHP"),
            *map_vars("BaseMP"),
            "BaseMissChance",
            "BaseSpellEffectiveness",
            *map_vars("BaseStaticHPRegen"),
            *map_vars("BaseStaticMPRegen"),
            "BotEnabled",
            "BotEnabledMM",
            "CastShadows",
            "ChampionId",
            "CharAudioNameOverride",
            "ChasingAttackRangePercent",
            "Classification",
            "CritDamageBonus",
            "CritPerLevel",
            "CS_easy",
            "CS_medium",
            "CS_hard",
            "DamagePerLevel",
            "DeathEventListeningRadius",
            "DeathTime",
            "DefenseRank",
            "DelayCastOffsetPercent",
            "DelayTotalTimePercent",
            "Description",
            "DifficultyRank",
            "DisableAggroIndicator",
            "DisableContinuousTargetFacing",
            "DisableGlobalDeathEffect",
            "DisableUltReadySounds",
            "DodgePerLevel",
            "DrawPARLikeHealth",
            "EnemyTooltip",
            "ExperienceRadius",
            "ExpGivenOnDeath",
            *[ v.format(a, x if x > 0 else  "") for a in [
                    "BaseAttack",
                    "BasicAttack",
                    "ExtraAttack",
                    "CritAttack",
                    "ExtraCritAttack",
                    "CriticalAttack",
                ] for v  in [
                    "{}{}",
                    "{}{}_AttackCastTime",
                    "{}{}_AttackCastDelayOffsetPercent",
                    "{}{}_AttackDelayCastOffsetPercent",
                    "{}{}_AttackDelayCastOffsetPercentAttackSpeedRatio",
                    "{}{}_AttackDelayOffsetPercent",
                    "{}{}_AttackTotalTime",
                    "{}{}_Probability",
                ] for x in range(0, 10)
            ],
            *[ "ExtraSpell{}".format(x) for x in range(0, 17) ],
            "FireworksEnabled",
            "FriendlyTooltip",
            "GameplayCollisionRadius",
            "GlobalExpGivenOnDeath",
            "GlobalGoldGivenOnDeath",
            "GoldGivenOnDeath",
            "GoldRadius",
            "HitFxScale",
            "HoverIndicatorRadius",
            "HoverIndicatorTextureName",
            "HoverLineIndicatorBaseTextureName",
            "HoverLineIndicatorTargetTextureName",
            "HoverLineIndicatorWidth",
            "HPPerLevel",
            "HPRegenPerLevel",
            "Immobile",
            "IsElite",
            "IsEpic",
            "IsImportantBotTarget",
            "IsMelee",
            "JointForAnimAdjustedSelection",
            "LevelDodge",
            "LevelSpellEffectiveness",
            "LocalExpGivenOnDeath",
            "LocalGoldGivenOnDeath",
            "LocalGoldSplitWithLastHitter",
            "Lore1",
            "Lore2",
            "MagicRank",
            "MaxLevels",
            "Metadata",
            "MonsterDataTableId",
            "MoveSpeed",
            "MPPerLevel",
            "MPRegenPerLevel",
            "Name",
            "NeverRender",
            "NoAutoAttack",
            "NoHealthBar",
            "OccludedUnitSelectableDistance",
            "OutlineBBoxExpansion",
            "PARColor",
            "PARDisplayThroughDeath",
            "PARFadeColor",
            "PARHasRegenText",
            "PARIncrements",
            "PARMaxSegments",
            "PARNameString",
            "PARType",
            *[ p.format(x) for x in range(1, 7) for p in [
                    "Passive{}",
                    "Passive{}Desc",
                    *[ "PassLev{{}}Desc{}".format(x) for x in range(0,7) ],
                    "Passive{}Icon",
                    *[ "Passive{{}}Level{}".format(x) for x in range(0,7) ],
                    *[ "Passive{{}}Effect{}".format(x) for x in range(0,7) ],
                    "Passive{}LuaName",
                    "Passive{}Name",
                    "Passive{}NumEffects",
                    "Passive{}Range",
                ]
            ],
            "PassiveSpell",
            "PathfindingCollisionRadius",
            "PerceptionBubbleRadius",
            "PlatformEnabled",
            "PostAttackMoveDelay",
            "RecordAsWard",
            "Roles",
            "SearchTags",
            "SelectionHeight",
            "SelectionRadius",
            "SequentialAutoAttacks",
            "ServerOnly",
            "ShouldFaceTarget",
            "Significance",
            "SkipDrawOutline",
            "SoulGivenOnDeath",
            *[ s % x for x in range(1, 5) for s in [
                    "Spell%d",
                    "Spell%dDesc",
                    "Spell%dDisplayName",
                    "SpellsUpLevels%d",
                ]
            ],
            *map_vars("SpellBlock"),
            *map_vars("SpellBlockPerLevel"),
            "SR_easy",
            "SR_medium",
            "SR_hard",
            "Tips1",
            "Tips2",
            "Tips3",
            "TowerTargetingPriorityBoost",
            "TriggersOrderAcknowledgementVO",
            "UnitTags",
            "UseChampionVisibility",
            "UseRingIconForKillCallout",
            "WeaponMaterial",
            "`WeaponMaterial",
            "WeaponMaterial1",
            "WeaponMaterial2",
            "WeaponMaterial3",
            "WeaponMaterial4",
        ]
    ],
    [
        [ "DefaultAnimations" ],
        [
            *[ "Animation%d" % x for x in range(1, 10) ],
            "NumberOfAnimations",
            "Significance",
        ]
    ],
    [
        [ "Evolution" ],
        [
            "EnabledWhileDead",
            "EvolveTitle",
            "Spell1EvolveDesc",
            "Spell1EvolveIcon",
            "Spell2EvolveDesc",
            "Spell2EvolveIcon",
            "Spell3EvolveDesc",
            "Spell3EvolveIcon",
            "Spell4EvolveDesc",
            "Spell4EvolveIcon",
        ]
    ],
    [
        [ "HealthBar" ],
        [
            "AttachToBone",
            "HPPerTick",
            "ParallaxOffset",
            "Scale",
            "ShowWhileUntargetable",
            "UnitBarKey",
            "WorldOffset",
            "XOffset",
            "YOffset",
        ]
    ],
    [
        [ "IdleParticles" ],
        [
            "BeamParticle",
            "BeamShouldAlwayStargetEnemy",
            "BeamTargetParticle",
            "ChampTargetingParticle",
            "GameplayCollisionRadius",
            "NumberOfParticles",
            "SelfIllumination",
            *[ "Particle%d" % x for x in range(0, 100) ],
            "TowerTargetingParticle",
            "TowerTargetingParticle2",
            "TowerTargetingParticle2Death",
        ]
    ],
    [
        [ *[ "Info{}".format(x if x > 0 else "") for x in range(0, 8) ] ],
        [
            "IconCircle",
            "IconCircleScale",
            "IconMinimap",
            "IconSquare",
        ]
    ],
    [
        [ "Interaction" ],
        [
            "DoubleSided",
            "IdleAnim",
            "RandomizeIdleAnimPhase",
        ]
    ],
    [
        [ *[ "MeshSkin{}".format(x if x > 0 else "") for x in range(0, 30) ] ],
        [
            "Animations",
            "ArmorMaterial",
            "AttributeFlags",
            "Body",
            "BrushAlphaOverride",
            "CastShadows",
            "ChampionSkinID",
            "ChampionSkinName",
            "DisablePreload",
            "EmissiveTexture",
            "ExtraCharacterPreloads",
            "Fresnel",
            "FresnelBlue",
            "FresnelGreen",
            "FresnelRed",
            "GlossTexture",
            "GlowFactor",
            "HPPerTick",
            "IconAvatar",
            "IsOpaque",
            *[ mat % x for x in range(0,5) for mat in [
                    "MaterialOverride%dBlendMode",
                    "MaterialOverride%dGlossTexture",
                    "MaterialOverride%dEmissiveTexture",
                    "MaterialOverride%dFixedAlphaScrolling",
                    "MaterialOverride%dPriority",
                    "MaterialOverride%dRenderingMode",
                    "MaterialOverride%dSubMesh",
                    "MaterialOverride%dTexture",
                    "MaterialOverride%dUVScroll",
                ]
            ],
            "MaterialOverrideTransMap",
            "MaterialOverrideTransSource",
            "MaterialOverridePriority",
            "OverrideBoundingBox",
            "ParallaxOffset",
            "ParticleOverride_ChampionKillDeathParticle",
            "ParticleOverride_DeathParticle",
            "ReflectionFresnel",
            "ReflectionFresnelBlue",
            "ReflectionFresnelGreen",
            "ReflectionFresnelRed",
            "ReflectionMap",
            "ReflectionOpacityDirect",
            "ReflectionOpacityGlancing",
            "Scale",
            "SelfIllumination",
            "SimpleSkin",
            "Skeleton",
            "SkinScale",
            "SkinAudioNameOverride",
            "SkipVOOverride",
            "SubmeshesToHide",
            "Texture",
            "TextureLow",
            "UsesSkinVO",
            "UnitBarKey",
            "VOOverride",
            "Weight",
            "WorldOffset",
            "XOffset",
            "YOffset",
        ]
    ],
    [
        [ "Minimap" ],
        [
            "MinimapIconOverride",
        ]
    ],
    [
        [ "Minion" ],
        [
            "AlwaysUpdatePAR",
            "AlwaysVisible",
            "IsTower",
        ]
    ],
    [
        [ "Package" ],
        [
            "FallbackPackage",
            "FallbackINI",
        ]
    ],
    [
        [ 
            "ItemSet1",
            "ItemSet2",
            "RecItems",
            "TutorialRecItems",
        ],
        [
            "SetName",
            *[ "RecItem%d" % x for x in range(1, 7) ],
        ]
    ],
    [
        [ "Sounds" ],
        [
            "Attack1",
            "Attack2",
            "Attack3",
            "Attack4",
            "Click1",
            "Click2",
            "Click3",
            "Click4",
            "Death",
            "Move1",
            "Move2",
            "Move3",
            "Move4",
            "Ready",
            "Special1",
            "Special2",
        ]
    ],
    [
        [ "Useable" ],
        [
            "AllyCanUse",
            "CooldownSpellSlot",
            "EnemyCanUse",
            "GoldRedirectTargetUseableOnly",
            "HeroUseSpell",
            "IsUseable",
            "MinionUseable",
            "MinionUseSpell",
        ]
    ]
]

all_inibin_fixdict = {
    h: (s, n) for sn in all_inibin_fixlist for s,n,h in a_ihash(*sn)
}

def get_fixdict(inib):
    return all_inibin_fixdict

# unhashes .inibin with dictionary
def fix(inib, fixd = None):
    if fixd == None:
        fixd = get_fixdict(inib)
    if not "Values" in inib:
        inib["Values"] = {}
    if not "UNKNOWN_HASHES" in inib:
        inib["UNKNOWN_HASHES"] = {}
    values = inib["Values"]
    unk = inib["UNKNOWN_HASHES"]

    for h, (s, n) in fixd.items():
        if h in unk:
            if not s in values:
                values[s] = {}
            values[s][n] = unk[h]
            del unk[h]
    
def fix_dry(inib, fixd = None):
    if fixd == None:
        fixd = get_fixdict(inib)
    return len(inib["UNKNOWN_HASHES"]), len((
        *(h for h in inib["UNKNOWN_HASHES"] if h in fixd),
    ))
